#!/bin/bash

# Script which converts a vsclib vbe cell to a wsclib one.

old_height=72
new_height=80

cp -p ../vsclib013/$1.vbe .
sed 's|;| ;|' $1.vbe | \
awk -v "FS= " '/^ *CONSTANT  *area / {printf "  %1s %1s          %1s %1s %1s %1s %1s\n", $1,$2,$3,$4,$5,$6*'$new_height'/'$old_height',$7 }
!/^ *CONSTANT  *area / {print}' | \
sed 's| ;|;|' > $$temp

mv -f $$temp $1.vbe

