
SHELL=/bin/bash

an2v0x05.vbe: ../../../magic/spice_vsclib013/an2/an2v0x05.pr
	echo "# Remake an2v0x05.vbe"
an2v0x1.vbe: ../../../magic/spice_vsclib013/an2/an2v0x1.pr
	echo "# Remake an2v0x1.vbe"
an2v0x2.vbe: ../../../magic/spice_vsclib013/an2/an2v0x2.pr
	echo "# Remake an2v0x2.vbe"
an2v0x3.vbe: ../../../magic/spice_vsclib013/an2/an2v0x3.pr
	echo "# Remake an2v0x3.vbe"
an2v0x4.vbe: ../../../magic/spice_vsclib013/an2/an2v0x4.pr
	echo "# Remake an2v0x4.vbe"
an2v0x6.vbe: ../../../magic/spice_vsclib013/an2/an2v0x6.pr
	echo "# Remake an2v0x6.vbe"
an2v0x8.vbe: ../../../magic/spice_vsclib013/an2/an2v0x8.pr
	echo "# Remake an2v0x8.vbe"
an2v2x2.vbe: ../../../magic/spice_vsclib013/an2/an2v2x2.pr
	echo "# Remake an2v2x2.vbe"
an2v4x1.vbe: ../../../magic/spice_vsclib013/an2/an2v4x1.pr
	echo "# Remake an2v4x1.vbe"
an2v4x2.vbe: ../../../magic/spice_vsclib013/an2/an2v4x2.pr
	echo "# Remake an2v4x2.vbe"
an2v4x4.vbe: ../../../magic/spice_vsclib013/an2/an2v4x4.pr
	echo "# Remake an2v4x4.vbe"
an2v4x8.vbe: ../../../magic/spice_vsclib013/an2/an2v4x8.pr
	echo "# Remake an2v4x8.vbe"
an3v0x05.vbe: ../../../magic/spice_vsclib013/an3/an3v0x05.pr
	echo "# Remake an3v0x05.vbe"
an3v0x1.vbe: ../../../magic/spice_vsclib013/an3/an3v0x1.pr
	echo "# Remake an3v0x1.vbe"
an3v0x2.vbe: ../../../magic/spice_vsclib013/an3/an3v0x2.pr
	echo "# Remake an3v0x2.vbe"
an3v0x4.vbe: ../../../magic/spice_vsclib013/an3/an3v0x4.pr
	echo "# Remake an3v0x4.vbe"
an3v4x1.vbe: ../../../magic/spice_vsclib013/an3/an3v4x1.pr
	echo "# Remake an3v4x1.vbe"
an3v4x2.vbe: ../../../magic/spice_vsclib013/an3/an3v4x2.pr
	echo "# Remake an3v4x2.vbe"
an3v6x05.vbe: ../../../magic/spice_vsclib013/an3/an3v6x05.pr
	echo "# Remake an3v6x05.vbe"
an4v0x05.vbe: ../../../magic/spice_vsclib013/an4/an4v0x05.pr
	echo "# Remake an4v0x05.vbe"
an4v0x1.vbe: ../../../magic/spice_vsclib013/an4/an4v0x1.pr
	echo "# Remake an4v0x1.vbe"
an4v0x2.vbe: ../../../magic/spice_vsclib013/an4/an4v0x2.pr
	echo "# Remake an4v0x2.vbe"
an4v0x4.vbe: ../../../magic/spice_vsclib013/an4/an4v0x4.pr
	echo "# Remake an4v0x4.vbe"
an4v4x1.vbe: ../../../magic/spice_vsclib013/an4/an4v4x1.pr
	echo "# Remake an4v4x1.vbe"
aoi112v0x05.vbe: ../../../magic/spice_vsclib013/aoi112/aoi112v0x05.pr
	echo "# Remake aoi112v0x05.vbe"
aoi211v0x05.vbe: ../../../magic/spice_vsclib013/aoi211/aoi211v0x05.pr
	echo "# Remake aoi211v0x05.vbe"
aoi211v0x1.vbe: ../../../magic/spice_vsclib013/aoi211/aoi211v0x1.pr
	echo "# Remake aoi211v0x1.vbe"
aoi211v0x2.vbe: ../../../magic/spice_vsclib013/aoi211/aoi211v0x2.pr
	echo "# Remake aoi211v0x2.vbe"
aoi211v5x05.vbe: ../../../magic/spice_vsclib013/aoi211/aoi211v5x05.pr
	echo "# Remake aoi211v5x05.vbe"
aoi21a2bv0x05.vbe: ../../../magic/spice_vsclib013/aoi21a2b/aoi21a2bv0x05.pr
	echo "# Remake aoi21a2bv0x05.vbe"
aoi21a2bv5x05.vbe: ../../../magic/spice_vsclib013/aoi21a2b/aoi21a2bv5x05.pr
	echo "# Remake aoi21a2bv5x05.vbe"
aoi21a2v0x05.vbe: ../../../magic/spice_vsclib013/aoi21a2/aoi21a2v0x05.pr
	echo "# Remake aoi21a2v0x05.vbe"
aoi21bv0x05.vbe: ../../../magic/spice_vsclib013/aoi21b/aoi21bv0x05.pr
	echo "# Remake aoi21bv0x05.vbe"
aoi21v0x05.vbe: ../../../magic/spice_vsclib013/aoi21/aoi21v0x05.pr
	echo "# Remake aoi21v0x05.vbe"
aoi21v0x1.vbe: ../../../magic/spice_vsclib013/aoi21/aoi21v0x1.pr
	echo "# Remake aoi21v0x1.vbe"
aoi21v0x2.vbe: ../../../magic/spice_vsclib013/aoi21/aoi21v0x2.pr
	echo "# Remake aoi21v0x2.vbe"
aoi22v0x05.vbe: ../../../magic/spice_vsclib013/aoi22/aoi22v0x05.pr
	echo "# Remake aoi22v0x05.vbe"
aoi22v0x1.vbe: ../../../magic/spice_vsclib013/aoi22/aoi22v0x1.pr
	echo "# Remake aoi22v0x1.vbe"
aoi22v0x2.vbe: ../../../magic/spice_vsclib013/aoi22/aoi22v0x2.pr
	echo "# Remake aoi22v0x2.vbe"
aoi22v0x3.vbe: ../../../magic/spice_vsclib013/aoi22/aoi22v0x3.pr
	echo "# Remake aoi22v0x3.vbe"
aoi22v0x4.vbe: ../../../magic/spice_vsclib013/aoi22/aoi22v0x4.pr
	echo "# Remake aoi22v0x4.vbe"
aoi22v5x05.vbe: ../../../magic/spice_vsclib013/aoi22/aoi22v5x05.pr
	echo "# Remake aoi22v5x05.vbe"
aoi31v0x05.vbe: ../../../magic/spice_vsclib013/aoi31/aoi31v0x05.pr
	echo "# Remake aoi31v0x05.vbe"
aoi31v0x1.vbe: ../../../magic/spice_vsclib013/aoi31/aoi31v0x1.pr
	echo "# Remake aoi31v0x1.vbe"
aoi31v0x2.vbe: ../../../magic/spice_vsclib013/aoi31/aoi31v0x2.pr
	echo "# Remake aoi31v0x2.vbe"
aoi31v0x3.vbe: ../../../magic/spice_vsclib013/aoi31/aoi31v0x3.pr
	echo "# Remake aoi31v0x3.vbe"
aon21bv0x05.vbe: ../../../magic/spice_vsclib013/aon21b/aon21bv0x05.pr
	echo "# Remake aon21bv0x05.vbe"
aon21bv0x1.vbe: ../../../magic/spice_vsclib013/aon21b/aon21bv0x1.pr
	echo "# Remake aon21bv0x1.vbe"
aon21bv0x2.vbe: ../../../magic/spice_vsclib013/aon21b/aon21bv0x2.pr
	echo "# Remake aon21bv0x2.vbe"
aon21bv0x3.vbe: ../../../magic/spice_vsclib013/aon21b/aon21bv0x3.pr
	echo "# Remake aon21bv0x3.vbe"
aon21bv0x4.vbe: ../../../magic/spice_vsclib013/aon21b/aon21bv0x4.pr
	echo "# Remake aon21bv0x4.vbe"
aon21v0x05.vbe: ../../../magic/spice_vsclib013/aon21/aon21v0x05.pr
	echo "# Remake aon21v0x05.vbe"
bf1v0x05.vbe: ../../../magic/spice_vsclib013/bf1/bf1v0x05.pr
	echo "# Remake bf1v0x05.vbe"
bf1v0x12.vbe: ../../../magic/spice_vsclib013/bf1/bf1v0x12.pr
	echo "# Remake bf1v0x12.vbe"
bf1v0x1.vbe: ../../../magic/spice_vsclib013/bf1/bf1v0x1.pr
	echo "# Remake bf1v0x1.vbe"
bf1v0x2.vbe: ../../../magic/spice_vsclib013/bf1/bf1v0x2.pr
	echo "# Remake bf1v0x2.vbe"
bf1v0x3.vbe: ../../../magic/spice_vsclib013/bf1/bf1v0x3.pr
	echo "# Remake bf1v0x3.vbe"
bf1v0x4.vbe: ../../../magic/spice_vsclib013/bf1/bf1v0x4.pr
	echo "# Remake bf1v0x4.vbe"
bf1v0x6.vbe: ../../../magic/spice_vsclib013/bf1/bf1v0x6.pr
	echo "# Remake bf1v0x6.vbe"
bf1v0x8.vbe: ../../../magic/spice_vsclib013/bf1/bf1v0x8.pr
	echo "# Remake bf1v0x8.vbe"
bf1v1x2.vbe: ../../../magic/spice_vsclib013/bf1/bf1v1x2.pr
	echo "# Remake bf1v1x2.vbe"
bf1v2x1.vbe: ../../../magic/spice_vsclib013/bf1/bf1v2x1.pr
	echo "# Remake bf1v2x1.vbe"
bf1v2x2.vbe: ../../../magic/spice_vsclib013/bf1/bf1v2x2.pr
	echo "# Remake bf1v2x2.vbe"
bf1v2x3.vbe: ../../../magic/spice_vsclib013/bf1/bf1v2x3.pr
	echo "# Remake bf1v2x3.vbe"
bf1v2x4.vbe: ../../../magic/spice_vsclib013/bf1/bf1v2x4.pr
	echo "# Remake bf1v2x4.vbe"
bf1v2x6.vbe: ../../../magic/spice_vsclib013/bf1/bf1v2x6.pr
	echo "# Remake bf1v2x6.vbe"
bf1v2x8.vbe: ../../../magic/spice_vsclib013/bf1/bf1v2x8.pr
	echo "# Remake bf1v2x8.vbe"
bf1v4x1.vbe: ../../../magic/spice_vsclib013/bf1/bf1v4x1.pr
	echo "# Remake bf1v4x1.vbe"
bf1v5x05.vbe: ../../../magic/spice_vsclib013/bf1/bf1v5x05.pr
	echo "# Remake bf1v5x05.vbe"
bf1v5x1.vbe: ../../../magic/spice_vsclib013/bf1/bf1v5x1.pr
	echo "# Remake bf1v5x1.vbe"
bf1v5x2.vbe: ../../../magic/spice_vsclib013/bf1/bf1v5x2.pr
	echo "# Remake bf1v5x2.vbe"
bf1v5x4.vbe: ../../../magic/spice_vsclib013/bf1/bf1v5x4.pr
	echo "# Remake bf1v5x4.vbe"
bf1v6x2.vbe: ../../../magic/spice_vsclib013/bf1/bf1v6x2.pr
	echo "# Remake bf1v6x2.vbe"
bf1v8x4.vbe: ../../../magic/spice_vsclib013/bf1/bf1v8x4.pr
	echo "# Remake bf1v8x4.vbe"
bsi2v2x1.vbe: ../../../magic/spice_vsclib013/bsi2/bsi2v2x1.pr
	echo "# Remake bsi2v2x1.vbe"
cgi2abv0x05.vbe: ../../../magic/spice_vsclib013/cgi2ab/cgi2abv0x05.pr
	echo "# Remake cgi2abv0x05.vbe"
cgi2abv0x1.vbe: ../../../magic/spice_vsclib013/cgi2ab/cgi2abv0x1.pr
	echo "# Remake cgi2abv0x1.vbe"
cgi2abv0x2.vbe: ../../../magic/spice_vsclib013/cgi2ab/cgi2abv0x2.pr
	echo "# Remake cgi2abv0x2.vbe"
cgi2bv0x05.vbe: ../../../magic/spice_vsclib013/cgi2b/cgi2bv0x05.pr
	echo "# Remake cgi2bv0x05.vbe"
cgi2bv0x1.vbe: ../../../magic/spice_vsclib013/cgi2b/cgi2bv0x1.pr
	echo "# Remake cgi2bv0x1.vbe"
cgi2bv0x2.vbe: ../../../magic/spice_vsclib013/cgi2b/cgi2bv0x2.pr
	echo "# Remake cgi2bv0x2.vbe"
cgi2bv0x3.vbe: ../../../magic/spice_vsclib013/cgi2b/cgi2bv0x3.pr
	echo "# Remake cgi2bv0x3.vbe"
cgi2cv0x05.vbe: ../../../magic/spice_vsclib013/cgi2c/cgi2cv0x05.pr
	echo "# Remake cgi2cv0x05.vbe"
cgi2cv0x1.vbe: ../../../magic/spice_vsclib013/cgi2c/cgi2cv0x1.pr
	echo "# Remake cgi2cv0x1.vbe"
cgi2cv0x2.vbe: ../../../magic/spice_vsclib013/cgi2c/cgi2cv0x2.pr
	echo "# Remake cgi2cv0x2.vbe"
cgi2cv0x3.vbe: ../../../magic/spice_vsclib013/cgi2c/cgi2cv0x3.pr
	echo "# Remake cgi2cv0x3.vbe"
cgi2v0x05.vbe: ../../../magic/spice_vsclib013/cgi2/cgi2v0x05.pr
	echo "# Remake cgi2v0x05.vbe"
cgi2v0x1.vbe: ../../../magic/spice_vsclib013/cgi2/cgi2v0x1.pr
	echo "# Remake cgi2v0x1.vbe"
cgi2v0x2.vbe: ../../../magic/spice_vsclib013/cgi2/cgi2v0x2.pr
	echo "# Remake cgi2v0x2.vbe"
cgi2v0x3.vbe: ../../../magic/spice_vsclib013/cgi2/cgi2v0x3.pr
	echo "# Remake cgi2v0x3.vbe"
dfnt1v0x2.vbe: ../../../magic/spice_vsclib013/dfnt1/dfnt1v0x2.pr
	echo "# Remake dfnt1v0x2.vbe"
dly1v0x05.vbe: ../../../magic/spice_vsclib013/dly1/dly1v0x05.pr
	echo "# Remake dly1v0x05.vbe"
dly2v0x05.vbe: ../../../magic/spice_vsclib013/dly2/dly2v0x05.pr
	echo "# Remake dly2v0x05.vbe"
dly2v0x1.vbe: ../../../magic/spice_vsclib013/dly2/dly2v0x1.pr
	echo "# Remake dly2v0x1.vbe"
ha2v0x2.vbe: ../../../magic/spice_vsclib013/ha2/ha2v0x2.pr
	echo "# Remake ha2v0x2.vbe"
iv1v0x05.vbe: ../../../magic/spice_vsclib013/iv1/iv1v0x05.pr
	echo "# Remake iv1v0x05.vbe"
iv1v0x12.vbe: ../../../magic/spice_vsclib013/iv1/iv1v0x12.pr
	echo "# Remake iv1v0x12.vbe"
iv1v0x1.vbe: ../../../magic/spice_vsclib013/iv1/iv1v0x1.pr
	echo "# Remake iv1v0x1.vbe"
iv1v0x2.vbe: ../../../magic/spice_vsclib013/iv1/iv1v0x2.pr
	echo "# Remake iv1v0x2.vbe"
iv1v0x3.vbe: ../../../magic/spice_vsclib013/iv1/iv1v0x3.pr
	echo "# Remake iv1v0x3.vbe"
iv1v0x4.vbe: ../../../magic/spice_vsclib013/iv1/iv1v0x4.pr
	echo "# Remake iv1v0x4.vbe"
iv1v0x6.vbe: ../../../magic/spice_vsclib013/iv1/iv1v0x6.pr
	echo "# Remake iv1v0x6.vbe"
iv1v0x8.vbe: ../../../magic/spice_vsclib013/iv1/iv1v0x8.pr
	echo "# Remake iv1v0x8.vbe"
iv1v1x05.vbe: ../../../magic/spice_vsclib013/iv1/iv1v1x05.pr
	echo "# Remake iv1v1x05.vbe"
iv1v1x1.vbe: ../../../magic/spice_vsclib013/iv1/iv1v1x1.pr
	echo "# Remake iv1v1x1.vbe"
iv1v1x2.vbe: ../../../magic/spice_vsclib013/iv1/iv1v1x2.pr
	echo "# Remake iv1v1x2.vbe"
iv1v1x4.vbe: ../../../magic/spice_vsclib013/iv1/iv1v1x4.pr
	echo "# Remake iv1v1x4.vbe"
iv1v1x8.vbe: ../../../magic/spice_vsclib013/iv1/iv1v1x8.pr
	echo "# Remake iv1v1x8.vbe"
iv1v2x2.vbe: ../../../magic/spice_vsclib013/iv1/iv1v2x2.pr
	echo "# Remake iv1v2x2.vbe"
iv1v3x1.vbe: ../../../magic/spice_vsclib013/iv1/iv1v3x1.pr
	echo "# Remake iv1v3x1.vbe"
iv1v3x3.vbe: ../../../magic/spice_vsclib013/iv1/iv1v3x3.pr
	echo "# Remake iv1v3x3.vbe"
iv1v3x6.vbe: ../../../magic/spice_vsclib013/iv1/iv1v3x6.pr
	echo "# Remake iv1v3x6.vbe"
iv1v4x12.vbe: ../../../magic/spice_vsclib013/iv1/iv1v4x12.pr
	echo "# Remake iv1v4x12.vbe"
iv1v4x1.vbe: ../../../magic/spice_vsclib013/iv1/iv1v4x1.pr
	echo "# Remake iv1v4x1.vbe"
iv1v4x2.vbe: ../../../magic/spice_vsclib013/iv1/iv1v4x2.pr
	echo "# Remake iv1v4x2.vbe"
iv1v4x3.vbe: ../../../magic/spice_vsclib013/iv1/iv1v4x3.pr
	echo "# Remake iv1v4x3.vbe"
iv1v4x4.vbe: ../../../magic/spice_vsclib013/iv1/iv1v4x4.pr
	echo "# Remake iv1v4x4.vbe"
iv1v4x6.vbe: ../../../magic/spice_vsclib013/iv1/iv1v4x6.pr
	echo "# Remake iv1v4x6.vbe"
iv1v4x8.vbe: ../../../magic/spice_vsclib013/iv1/iv1v4x8.pr
	echo "# Remake iv1v4x8.vbe"
iv1v5x12.vbe: ../../../magic/spice_vsclib013/iv1/iv1v5x12.pr
	echo "# Remake iv1v5x12.vbe"
iv1v5x1.vbe: ../../../magic/spice_vsclib013/iv1/iv1v5x1.pr
	echo "# Remake iv1v5x1.vbe"
iv1v5x2.vbe: ../../../magic/spice_vsclib013/iv1/iv1v5x2.pr
	echo "# Remake iv1v5x2.vbe"
iv1v5x3.vbe: ../../../magic/spice_vsclib013/iv1/iv1v5x3.pr
	echo "# Remake iv1v5x3.vbe"
iv1v5x4.vbe: ../../../magic/spice_vsclib013/iv1/iv1v5x4.pr
	echo "# Remake iv1v5x4.vbe"
iv1v5x6.vbe: ../../../magic/spice_vsclib013/iv1/iv1v5x6.pr
	echo "# Remake iv1v5x6.vbe"
iv1v5x8.vbe: ../../../magic/spice_vsclib013/iv1/iv1v5x8.pr
	echo "# Remake iv1v5x8.vbe"
iv1v6x1.vbe: ../../../magic/spice_vsclib013/iv1/iv1v6x1.pr
	echo "# Remake iv1v6x1.vbe"
iv1v6x2.vbe: ../../../magic/spice_vsclib013/iv1/iv1v6x2.pr
	echo "# Remake iv1v6x2.vbe"
iv1v7x1.vbe: ../../../magic/spice_vsclib013/iv1/iv1v7x1.pr
	echo "# Remake iv1v7x1.vbe"
iv1v8x1.vbe: ../../../magic/spice_vsclib013/iv1/iv1v8x1.pr
	echo "# Remake iv1v8x1.vbe"
mxi2v0x05.vbe: ../../../magic/spice_vsclib013/mxi2/mxi2v0x05.pr
	echo "# Remake mxi2v0x05.vbe"
mxi2v0x1.vbe: ../../../magic/spice_vsclib013/mxi2/mxi2v0x1.pr
	echo "# Remake mxi2v0x1.vbe"
mxi2v0x2.vbe: ../../../magic/spice_vsclib013/mxi2/mxi2v0x2.pr
	echo "# Remake mxi2v0x2.vbe"
mxi2v2x05.vbe: ../../../magic/spice_vsclib013/mxi2/mxi2v2x05.pr
	echo "# Remake mxi2v2x05.vbe"
mxi2v2x1.vbe: ../../../magic/spice_vsclib013/mxi2/mxi2v2x1.pr
	echo "# Remake mxi2v2x1.vbe"
mxi2v2x2.vbe: ../../../magic/spice_vsclib013/mxi2/mxi2v2x2.pr
	echo "# Remake mxi2v2x2.vbe"
mxi2v2x3.vbe: ../../../magic/spice_vsclib013/mxi2/mxi2v2x3.pr
	echo "# Remake mxi2v2x3.vbe"
mxi2v2x4.vbe: ../../../magic/spice_vsclib013/mxi2/mxi2v2x4.pr
	echo "# Remake mxi2v2x4.vbe"
mxn2v0x05.vbe: ../../../magic/spice_vsclib013/mxn2/mxn2v0x05.pr
	echo "# Remake mxn2v0x05.vbe"
mxn2v0x1.vbe: ../../../magic/spice_vsclib013/mxn2/mxn2v0x1.pr
	echo "# Remake mxn2v0x1.vbe"
mxn2v2x1.vbe: ../../../magic/spice_vsclib013/mxn2/mxn2v2x1.pr
	echo "# Remake mxn2v2x1.vbe"
nd2abv0x05.vbe: ../../../magic/spice_vsclib013/nd2ab/nd2abv0x05.pr
	echo "# Remake nd2abv0x05.vbe"
nd2abv0x1.vbe: ../../../magic/spice_vsclib013/nd2ab/nd2abv0x1.pr
	echo "# Remake nd2abv0x1.vbe"
nd2abv0x2.vbe: ../../../magic/spice_vsclib013/nd2ab/nd2abv0x2.pr
	echo "# Remake nd2abv0x2.vbe"
nd2abv0x3.vbe: ../../../magic/spice_vsclib013/nd2ab/nd2abv0x3.pr
	echo "# Remake nd2abv0x3.vbe"
nd2abv0x4.vbe: ../../../magic/spice_vsclib013/nd2ab/nd2abv0x4.pr
	echo "# Remake nd2abv0x4.vbe"
nd2av0x05.vbe: ../../../magic/spice_vsclib013/nd2a/nd2av0x05.pr
	echo "# Remake nd2av0x05.vbe"
nd2av0x1.vbe: ../../../magic/spice_vsclib013/nd2a/nd2av0x1.pr
	echo "# Remake nd2av0x1.vbe"
nd2av0x2.vbe: ../../../magic/spice_vsclib013/nd2a/nd2av0x2.pr
	echo "# Remake nd2av0x2.vbe"
nd2av0x3.vbe: ../../../magic/spice_vsclib013/nd2a/nd2av0x3.pr
	echo "# Remake nd2av0x3.vbe"
nd2av0x4.vbe: ../../../magic/spice_vsclib013/nd2a/nd2av0x4.pr
	echo "# Remake nd2av0x4.vbe"
nd2av0x6.vbe: ../../../magic/spice_vsclib013/nd2a/nd2av0x6.pr
	echo "# Remake nd2av0x6.vbe"
nd2av0x8.vbe: ../../../magic/spice_vsclib013/nd2a/nd2av0x8.pr
	echo "# Remake nd2av0x8.vbe"
nd2v0x05.vbe: ../../../magic/spice_vsclib013/nd2/nd2v0x05.pr
	echo "# Remake nd2v0x05.vbe"
nd2v0x1.vbe: ../../../magic/spice_vsclib013/nd2/nd2v0x1.pr
	echo "# Remake nd2v0x1.vbe"
nd2v0x2.vbe: ../../../magic/spice_vsclib013/nd2/nd2v0x2.pr
	echo "# Remake nd2v0x2.vbe"
nd2v0x3.vbe: ../../../magic/spice_vsclib013/nd2/nd2v0x3.pr
	echo "# Remake nd2v0x3.vbe"
nd2v0x4.vbe: ../../../magic/spice_vsclib013/nd2/nd2v0x4.pr
	echo "# Remake nd2v0x4.vbe"
nd2v0x6.vbe: ../../../magic/spice_vsclib013/nd2/nd2v0x6.pr
	echo "# Remake nd2v0x6.vbe"
nd2v0x8.vbe: ../../../magic/spice_vsclib013/nd2/nd2v0x8.pr
	echo "# Remake nd2v0x8.vbe"
nd2v3x05.vbe: ../../../magic/spice_vsclib013/nd2/nd2v3x05.pr
	echo "# Remake nd2v3x05.vbe"
nd2v3x1.vbe: ../../../magic/spice_vsclib013/nd2/nd2v3x1.pr
	echo "# Remake nd2v3x1.vbe"
nd2v3x2.vbe: ../../../magic/spice_vsclib013/nd2/nd2v3x2.pr
	echo "# Remake nd2v3x2.vbe"
nd2v3x3.vbe: ../../../magic/spice_vsclib013/nd2/nd2v3x3.pr
	echo "# Remake nd2v3x3.vbe"
nd2v3x4.vbe: ../../../magic/spice_vsclib013/nd2/nd2v3x4.pr
	echo "# Remake nd2v3x4.vbe"
nd2v4x1.vbe: ../../../magic/spice_vsclib013/nd2/nd2v4x1.pr
	echo "# Remake nd2v4x1.vbe"
nd2v4x2.vbe: ../../../magic/spice_vsclib013/nd2/nd2v4x2.pr
	echo "# Remake nd2v4x2.vbe"
nd2v4x3.vbe: ../../../magic/spice_vsclib013/nd2/nd2v4x3.pr
	echo "# Remake nd2v4x3.vbe"
nd2v4x4.vbe: ../../../magic/spice_vsclib013/nd2/nd2v4x4.pr
	echo "# Remake nd2v4x4.vbe"
nd2v4x6.vbe: ../../../magic/spice_vsclib013/nd2/nd2v4x6.pr
	echo "# Remake nd2v4x6.vbe"
nd2v4x8.vbe: ../../../magic/spice_vsclib013/nd2/nd2v4x8.pr
	echo "# Remake nd2v4x8.vbe"
nd2v5x05.vbe: ../../../magic/spice_vsclib013/nd2/nd2v5x05.pr
	echo "# Remake nd2v5x05.vbe"
nd2v5x1.vbe: ../../../magic/spice_vsclib013/nd2/nd2v5x1.pr
	echo "# Remake nd2v5x1.vbe"
nd2v5x2.vbe: ../../../magic/spice_vsclib013/nd2/nd2v5x2.pr
	echo "# Remake nd2v5x2.vbe"
nd2v5x3.vbe: ../../../magic/spice_vsclib013/nd2/nd2v5x3.pr
	echo "# Remake nd2v5x3.vbe"
nd2v5x4.vbe: ../../../magic/spice_vsclib013/nd2/nd2v5x4.pr
	echo "# Remake nd2v5x4.vbe"
nd2v5x6.vbe: ../../../magic/spice_vsclib013/nd2/nd2v5x6.pr
	echo "# Remake nd2v5x6.vbe"
nd2v5x8.vbe: ../../../magic/spice_vsclib013/nd2/nd2v5x8.pr
	echo "# Remake nd2v5x8.vbe"
nd2v6x3.vbe: ../../../magic/spice_vsclib013/nd2/nd2v6x3.pr
	echo "# Remake nd2v6x3.vbe"
nd3abv0x05.vbe: ../../../magic/spice_vsclib013/nd3ab/nd3abv0x05.pr
	echo "# Remake nd3abv0x05.vbe"
nd3av0x05.vbe: ../../../magic/spice_vsclib013/nd3a/nd3av0x05.pr
	echo "# Remake nd3av0x05.vbe"
nd3v0x05.vbe: ../../../magic/spice_vsclib013/nd3/nd3v0x05.pr
	echo "# Remake nd3v0x05.vbe"
nd3v0x1.vbe: ../../../magic/spice_vsclib013/nd3/nd3v0x1.pr
	echo "# Remake nd3v0x1.vbe"
nd3v0x2.vbe: ../../../magic/spice_vsclib013/nd3/nd3v0x2.pr
	echo "# Remake nd3v0x2.vbe"
nd3v0x3.vbe: ../../../magic/spice_vsclib013/nd3/nd3v0x3.pr
	echo "# Remake nd3v0x3.vbe"
nd3v0x4.vbe: ../../../magic/spice_vsclib013/nd3/nd3v0x4.pr
	echo "# Remake nd3v0x4.vbe"
nd3v0x6.vbe: ../../../magic/spice_vsclib013/nd3/nd3v0x6.pr
	echo "# Remake nd3v0x6.vbe"
nd3v5x2.vbe: ../../../magic/spice_vsclib013/nd3/nd3v5x2.pr
	echo "# Remake nd3v5x2.vbe"
nd3v5x3.vbe: ../../../magic/spice_vsclib013/nd3/nd3v5x3.pr
	echo "# Remake nd3v5x3.vbe"
nd3v5x4.vbe: ../../../magic/spice_vsclib013/nd3/nd3v5x4.pr
	echo "# Remake nd3v5x4.vbe"
nd3v5x6.vbe: ../../../magic/spice_vsclib013/nd3/nd3v5x6.pr
	echo "# Remake nd3v5x6.vbe"
nd3v6x6.vbe: ../../../magic/spice_vsclib013/nd3/nd3v6x6.pr
	echo "# Remake nd3v6x6.vbe"
nd4v0x05.vbe: ../../../magic/spice_vsclib013/nd4/nd4v0x05.pr
	echo "# Remake nd4v0x05.vbe"
nd4v0x1.vbe: ../../../magic/spice_vsclib013/nd4/nd4v0x1.pr
	echo "# Remake nd4v0x1.vbe"
nd4v0x2.vbe: ../../../magic/spice_vsclib013/nd4/nd4v0x2.pr
	echo "# Remake nd4v0x2.vbe"
nd4v0x3.vbe: ../../../magic/spice_vsclib013/nd4/nd4v0x3.pr
	echo "# Remake nd4v0x3.vbe"
nr2av0x1.vbe: ../../../magic/spice_vsclib013/nr2a/nr2av0x1.pr
	echo "# Remake nr2av0x1.vbe"
nr2av0x2.vbe: ../../../magic/spice_vsclib013/nr2a/nr2av0x2.pr
	echo "# Remake nr2av0x2.vbe"
nr2av0x3.vbe: ../../../magic/spice_vsclib013/nr2a/nr2av0x3.pr
	echo "# Remake nr2av0x3.vbe"
nr2av0x4.vbe: ../../../magic/spice_vsclib013/nr2a/nr2av0x4.pr
	echo "# Remake nr2av0x4.vbe"
nr2av0x6.vbe: ../../../magic/spice_vsclib013/nr2a/nr2av0x6.pr
	echo "# Remake nr2av0x6.vbe"
nr2av1x05.vbe: ../../../magic/spice_vsclib013/nr2a/nr2av1x05.pr
	echo "# Remake nr2av1x05.vbe"
nr2v0x05.vbe: ../../../magic/spice_vsclib013/nr2/nr2v0x05.pr
	echo "# Remake nr2v0x05.vbe"
nr2v0x1.vbe: ../../../magic/spice_vsclib013/nr2/nr2v0x1.pr
	echo "# Remake nr2v0x1.vbe"
nr2v0x2.vbe: ../../../magic/spice_vsclib013/nr2/nr2v0x2.pr
	echo "# Remake nr2v0x2.vbe"
nr2v0x3.vbe: ../../../magic/spice_vsclib013/nr2/nr2v0x3.pr
	echo "# Remake nr2v0x3.vbe"
nr2v0x4.vbe: ../../../magic/spice_vsclib013/nr2/nr2v0x4.pr
	echo "# Remake nr2v0x4.vbe"
nr2v0x6.vbe: ../../../magic/spice_vsclib013/nr2/nr2v0x6.pr
	echo "# Remake nr2v0x6.vbe"
nr2v0x8.vbe: ../../../magic/spice_vsclib013/nr2/nr2v0x8.pr
	echo "# Remake nr2v0x8.vbe"
nr2v1x05.vbe: ../../../magic/spice_vsclib013/nr2/nr2v1x05.pr
	echo "# Remake nr2v1x05.vbe"
nr2v1x1.vbe: ../../../magic/spice_vsclib013/nr2/nr2v1x1.pr
	echo "# Remake nr2v1x1.vbe"
nr2v1x2.vbe: ../../../magic/spice_vsclib013/nr2/nr2v1x2.pr
	echo "# Remake nr2v1x2.vbe"
nr2v1x3.vbe: ../../../magic/spice_vsclib013/nr2/nr2v1x3.pr
	echo "# Remake nr2v1x3.vbe"
nr2v1x4.vbe: ../../../magic/spice_vsclib013/nr2/nr2v1x4.pr
	echo "# Remake nr2v1x4.vbe"
nr2v1x6.vbe: ../../../magic/spice_vsclib013/nr2/nr2v1x6.pr
	echo "# Remake nr2v1x6.vbe"
nr2v1x8.vbe: ../../../magic/spice_vsclib013/nr2/nr2v1x8.pr
	echo "# Remake nr2v1x8.vbe"
nr3abv0x05.vbe: ../../../magic/spice_vsclib013/nr3ab/nr3abv0x05.pr
	echo "# Remake nr3abv0x05.vbe"
nr3av0x05.vbe: ../../../magic/spice_vsclib013/nr3a/nr3av0x05.pr
	echo "# Remake nr3av0x05.vbe"
nr3v0x05.vbe: ../../../magic/spice_vsclib013/nr3/nr3v0x05.pr
	echo "# Remake nr3v0x05.vbe"
nr3v0x1.vbe: ../../../magic/spice_vsclib013/nr3/nr3v0x1.pr
	echo "# Remake nr3v0x1.vbe"
nr3v0x2.vbe: ../../../magic/spice_vsclib013/nr3/nr3v0x2.pr
	echo "# Remake nr3v0x2.vbe"
nr3v0x3.vbe: ../../../magic/spice_vsclib013/nr3/nr3v0x3.pr
	echo "# Remake nr3v0x3.vbe"
nr3v0x4.vbe: ../../../magic/spice_vsclib013/nr3/nr3v0x4.pr
	echo "# Remake nr3v0x4.vbe"
nr3v1x05.vbe: ../../../magic/spice_vsclib013/nr3/nr3v1x05.pr
	echo "# Remake nr3v1x05.vbe"
nr4v0x1.vbe: ../../../magic/spice_vsclib013/nr4/nr4v0x1.pr
	echo "# Remake nr4v0x1.vbe"
nr4v0x2.vbe: ../../../magic/spice_vsclib013/nr4/nr4v0x2.pr
	echo "# Remake nr4v0x2.vbe"
nr4v1x05.vbe: ../../../magic/spice_vsclib013/nr4/nr4v1x05.pr
	echo "# Remake nr4v1x05.vbe"
oai211v0x05.vbe: ../../../magic/spice_vsclib013/oai211/oai211v0x05.pr
	echo "# Remake oai211v0x05.vbe"
oai211v0x1.vbe: ../../../magic/spice_vsclib013/oai211/oai211v0x1.pr
	echo "# Remake oai211v0x1.vbe"
oai21a2bv0x05.vbe: ../../../magic/spice_vsclib013/oai21a2b/oai21a2bv0x05.pr
	echo "# Remake oai21a2bv0x05.vbe"
oai21a2v0x05.vbe: ../../../magic/spice_vsclib013/oai21a2/oai21a2v0x05.pr
	echo "# Remake oai21a2v0x05.vbe"
oai21a2v0x1.vbe: ../../../magic/spice_vsclib013/oai21a2/oai21a2v0x1.pr
	echo "# Remake oai21a2v0x1.vbe"
oai21bv0x05.vbe: ../../../magic/spice_vsclib013/oai21b/oai21bv0x05.pr
	echo "# Remake oai21bv0x05.vbe"
oai21v0x05.vbe: ../../../magic/spice_vsclib013/oai21/oai21v0x05.pr
	echo "# Remake oai21v0x05.vbe"
oai21v0x1.vbe: ../../../magic/spice_vsclib013/oai21/oai21v0x1.pr
	echo "# Remake oai21v0x1.vbe"
oai21v0x2.vbe: ../../../magic/spice_vsclib013/oai21/oai21v0x2.pr
	echo "# Remake oai21v0x2.vbe"
oai21v0x3.vbe: ../../../magic/spice_vsclib013/oai21/oai21v0x3.pr
	echo "# Remake oai21v0x3.vbe"
oai21v0x4.vbe: ../../../magic/spice_vsclib013/oai21/oai21v0x4.pr
	echo "# Remake oai21v0x4.vbe"
oai21v0x6.vbe: ../../../magic/spice_vsclib013/oai21/oai21v0x6.pr
	echo "# Remake oai21v0x6.vbe"
oai21v0x8.vbe: ../../../magic/spice_vsclib013/oai21/oai21v0x8.pr
	echo "# Remake oai21v0x8.vbe"
oai22v0x05.vbe: ../../../magic/spice_vsclib013/oai22/oai22v0x05.pr
	echo "# Remake oai22v0x05.vbe"
oai22v0x1.vbe: ../../../magic/spice_vsclib013/oai22/oai22v0x1.pr
	echo "# Remake oai22v0x1.vbe"
oai22v0x2.vbe: ../../../magic/spice_vsclib013/oai22/oai22v0x2.pr
	echo "# Remake oai22v0x2.vbe"
oai23av0x05.vbe: ../../../magic/spice_vsclib013/oai23a/oai23av0x05.pr
	echo "# Remake oai23av0x05.vbe"
oai31v0x05.vbe: ../../../magic/spice_vsclib013/oai31/oai31v0x05.pr
	echo "# Remake oai31v0x05.vbe"
oai31v0x1.vbe: ../../../magic/spice_vsclib013/oai31/oai31v0x1.pr
	echo "# Remake oai31v0x1.vbe"
oai31v0x2.vbe: ../../../magic/spice_vsclib013/oai31/oai31v0x2.pr
	echo "# Remake oai31v0x2.vbe"
oan21bv0x05.vbe: ../../../magic/spice_vsclib013/oan21b/oan21bv0x05.pr
	echo "# Remake oan21bv0x05.vbe"
oan21v0x05.vbe: ../../../magic/spice_vsclib013/oan21/oan21v0x05.pr
	echo "# Remake oan21v0x05.vbe"
or2v0x05.vbe: ../../../magic/spice_vsclib013/or2/or2v0x05.pr
	echo "# Remake or2v0x05.vbe"
or2v0x1.vbe: ../../../magic/spice_vsclib013/or2/or2v0x1.pr
	echo "# Remake or2v0x1.vbe"
or2v0x2.vbe: ../../../magic/spice_vsclib013/or2/or2v0x2.pr
	echo "# Remake or2v0x2.vbe"
or2v0x3.vbe: ../../../magic/spice_vsclib013/or2/or2v0x3.pr
	echo "# Remake or2v0x3.vbe"
or2v0x4.vbe: ../../../magic/spice_vsclib013/or2/or2v0x4.pr
	echo "# Remake or2v0x4.vbe"
or2v0x8.vbe: ../../../magic/spice_vsclib013/or2/or2v0x8.pr
	echo "# Remake or2v0x8.vbe"
or2v4x1.vbe: ../../../magic/spice_vsclib013/or2/or2v4x1.pr
	echo "# Remake or2v4x1.vbe"
or2v7x2.vbe: ../../../magic/spice_vsclib013/or2/or2v7x2.pr
	echo "# Remake or2v7x2.vbe"
or3v0x05.vbe: ../../../magic/spice_vsclib013/or3/or3v0x05.pr
	echo "# Remake or3v0x05.vbe"
or3v0x1.vbe: ../../../magic/spice_vsclib013/or3/or3v0x1.pr
	echo "# Remake or3v0x1.vbe"
or3v0x2.vbe: ../../../magic/spice_vsclib013/or3/or3v0x2.pr
	echo "# Remake or3v0x2.vbe"
or3v0x3.vbe: ../../../magic/spice_vsclib013/or3/or3v0x3.pr
	echo "# Remake or3v0x3.vbe"
or3v0x4.vbe: ../../../magic/spice_vsclib013/or3/or3v0x4.pr
	echo "# Remake or3v0x4.vbe"
or3v3x2.vbe: ../../../magic/spice_vsclib013/or3/or3v3x2.pr
	echo "# Remake or3v3x2.vbe"
or3v4x05.vbe: ../../../magic/spice_vsclib013/or3/or3v4x05.pr
	echo "# Remake or3v4x05.vbe"
or4v0x05.vbe: ../../../magic/spice_vsclib013/or4/or4v0x05.pr
	echo "# Remake or4v0x05.vbe"
or4v0x1.vbe: ../../../magic/spice_vsclib013/or4/or4v0x1.pr
	echo "# Remake or4v0x1.vbe"
or4v0x2.vbe: ../../../magic/spice_vsclib013/or4/or4v0x2.pr
	echo "# Remake or4v0x2.vbe"
or4v0x3.vbe: ../../../magic/spice_vsclib013/or4/or4v0x3.pr
	echo "# Remake or4v0x3.vbe"
or4v3x2.vbe: ../../../magic/spice_vsclib013/or4/or4v3x2.pr
	echo "# Remake or4v3x2.vbe"
or4v4x05.vbe: ../../../magic/spice_vsclib013/or4/or4v4x05.pr
	echo "# Remake or4v4x05.vbe"
xaoi21v0x05.vbe: ../../../magic/spice_vsclib013/xaoi21/xaoi21v0x05.pr
	echo "# Remake xaoi21v0x05.vbe"
xaoi21v0x1.vbe: ../../../magic/spice_vsclib013/xaoi21/xaoi21v0x1.pr
	echo "# Remake xaoi21v0x1.vbe"
xaoi21v0x2.vbe: ../../../magic/spice_vsclib013/xaoi21/xaoi21v0x2.pr
	echo "# Remake xaoi21v0x2.vbe"
xaon21v0x05.vbe: ../../../magic/spice_vsclib013/xaon21/xaon21v0x05.pr
	echo "# Remake xaon21v0x05.vbe"
xaon21v0x1.vbe: ../../../magic/spice_vsclib013/xaon21/xaon21v0x1.pr
	echo "# Remake xaon21v0x1.vbe"
xaon21v0x2.vbe: ../../../magic/spice_vsclib013/xaon21/xaon21v0x2.pr
	echo "# Remake xaon21v0x2.vbe"
xaon21v0x3.vbe: ../../../magic/spice_vsclib013/xaon21/xaon21v0x3.pr
	echo "# Remake xaon21v0x3.vbe"
xnai21v0x05.vbe: ../../../magic/spice_vsclib013/xnai21/xnai21v0x05.pr
	echo "# Remake xnai21v0x05.vbe"
xnai21v1x05.vbe: ../../../magic/spice_vsclib013/xnai21/xnai21v1x05.pr
	echo "# Remake xnai21v1x05.vbe"
xnai21v2x05.vbe: ../../../magic/spice_vsclib013/xnai21/xnai21v2x05.pr
	echo "# Remake xnai21v2x05.vbe"
xnr2v0x05.vbe: ../../../magic/spice_vsclib013/xnr2/xnr2v0x05.pr
	echo "# Remake xnr2v0x05.vbe"
xnr2v0x1.vbe: ../../../magic/spice_vsclib013/xnr2/xnr2v0x1.pr
	echo "# Remake xnr2v0x1.vbe"
xnr2v0x2.vbe: ../../../magic/spice_vsclib013/xnr2/xnr2v0x2.pr
	echo "# Remake xnr2v0x2.vbe"
xnr2v0x3.vbe: ../../../magic/spice_vsclib013/xnr2/xnr2v0x3.pr
	echo "# Remake xnr2v0x3.vbe"
xnr2v0x4.vbe: ../../../magic/spice_vsclib013/xnr2/xnr2v0x4.pr
	echo "# Remake xnr2v0x4.vbe"
xnr2v6x1.vbe: ../../../magic/spice_vsclib013/xnr2/xnr2v6x1.pr
	echo "# Remake xnr2v6x1.vbe"
xnr2v8x05.vbe: ../../../magic/spice_vsclib013/xnr2/xnr2v8x05.pr
	echo "# Remake xnr2v8x05.vbe"
xnr3v1x05.vbe: ../../../magic/spice_vsclib013/xnr3/xnr3v1x05.pr
	echo "# Remake xnr3v1x05.vbe"
xnr3v1x1.vbe: ../../../magic/spice_vsclib013/xnr3/xnr3v1x1.pr
	echo "# Remake xnr3v1x1.vbe"
xnr3v1x2.vbe: ../../../magic/spice_vsclib013/xnr3/xnr3v1x2.pr
	echo "# Remake xnr3v1x2.vbe"
xooi21v0x05.vbe: ../../../magic/spice_vsclib013/xooi21/xooi21v0x05.pr
	echo "# Remake xooi21v0x05.vbe"
xooi21v0x1.vbe: ../../../magic/spice_vsclib013/xooi21/xooi21v0x1.pr
	echo "# Remake xooi21v0x1.vbe"
xooi21v0x2.vbe: ../../../magic/spice_vsclib013/xooi21/xooi21v0x2.pr
	echo "# Remake xooi21v0x2.vbe"
xoon21v0x05.vbe: ../../../magic/spice_vsclib013/xoon21/xoon21v0x05.pr
	echo "# Remake xoon21v0x05.vbe"
xoon21v0x1.vbe: ../../../magic/spice_vsclib013/xoon21/xoon21v0x1.pr
	echo "# Remake xoon21v0x1.vbe"
xoon21v0x2.vbe: ../../../magic/spice_vsclib013/xoon21/xoon21v0x2.pr
	echo "# Remake xoon21v0x2.vbe"
xoon21v0x3.vbe: ../../../magic/spice_vsclib013/xoon21/xoon21v0x3.pr
	echo "# Remake xoon21v0x3.vbe"
xor2v0x05.vbe: ../../../magic/spice_vsclib013/xor2/xor2v0x05.pr
	echo "# Remake xor2v0x05.vbe"
xor2v0x1.vbe: ../../../magic/spice_vsclib013/xor2/xor2v0x1.pr
	echo "# Remake xor2v0x1.vbe"
xor2v0x2.vbe: ../../../magic/spice_vsclib013/xor2/xor2v0x2.pr
	echo "# Remake xor2v0x2.vbe"
xor2v0x3.vbe: ../../../magic/spice_vsclib013/xor2/xor2v0x3.pr
	echo "# Remake xor2v0x3.vbe"
xor2v0x4.vbe: ../../../magic/spice_vsclib013/xor2/xor2v0x4.pr
	echo "# Remake xor2v0x4.vbe"
xor2v0x6.vbe: ../../../magic/spice_vsclib013/xor2/xor2v0x6.pr
	echo "# Remake xor2v0x6.vbe"
xor2v1x05.vbe: ../../../magic/spice_vsclib013/xor2/xor2v1x05.pr
	echo "# Remake xor2v1x05.vbe"
xor2v1x1.vbe: ../../../magic/spice_vsclib013/xor2/xor2v1x1.pr
	echo "# Remake xor2v1x1.vbe"
xor2v2x05.vbe: ../../../magic/spice_vsclib013/xor2/xor2v2x05.pr
	echo "# Remake xor2v2x05.vbe"
xor2v2x1.vbe: ../../../magic/spice_vsclib013/xor2/xor2v2x1.pr
	echo "# Remake xor2v2x1.vbe"
xor2v2x2.vbe: ../../../magic/spice_vsclib013/xor2/xor2v2x2.pr
	echo "# Remake xor2v2x2.vbe"
xor2v3x1.vbe: ../../../magic/spice_vsclib013/xor2/xor2v3x1.pr
	echo "# Remake xor2v3x1.vbe"
xor2v4x1.vbe: ../../../magic/spice_vsclib013/xor2/xor2v4x1.pr
	echo "# Remake xor2v4x1.vbe"
xor2v5x1.vbe: ../../../magic/spice_vsclib013/xor2/xor2v5x1.pr
	echo "# Remake xor2v5x1.vbe"
xor2v6x1.vbe: ../../../magic/spice_vsclib013/xor2/xor2v6x1.pr
	echo "# Remake xor2v6x1.vbe"
xor2v7x1.vbe: ../../../magic/spice_vsclib013/xor2/xor2v7x1.pr
	echo "# Remake xor2v7x1.vbe"
xor2v8x05.vbe: ../../../magic/spice_vsclib013/xor2/xor2v8x05.pr
	echo "# Remake xor2v8x05.vbe"
xor2v8x1.vbe: ../../../magic/spice_vsclib013/xor2/xor2v8x1.pr
	echo "# Remake xor2v8x1.vbe"
xor2v8x2.vbe: ../../../magic/spice_vsclib013/xor2/xor2v8x2.pr
	echo "# Remake xor2v8x2.vbe"
xor3v0x05.vbe: ../../../magic/spice_vsclib013/xor3/xor3v0x05.pr
	echo "# Remake xor3v0x05.vbe"
xor3v1x05.vbe: ../../../magic/spice_vsclib013/xor3/xor3v1x05.pr
	echo "# Remake xor3v1x05.vbe"
xor3v1x1.vbe: ../../../magic/spice_vsclib013/xor3/xor3v1x1.pr
	echo "# Remake xor3v1x1.vbe"
xor3v1x2.vbe: ../../../magic/spice_vsclib013/xor3/xor3v1x2.pr
	echo "# Remake xor3v1x2.vbe"
