#!/bin/bash

if [ $# -eq 0 ]
then
  echo '# Script which copies all the cells in ../sxlib100 across,'
  echo '# adding the value in argument 1 to their input pin capacitances.'
  exit 1
fi

source_dir=../sxlib100
catal_name=SXLIB100
inccap=$1

allcells=$(cat $source_dir/$catal_name | cut -f1 -d' ')

rm -f *.vbe
for cell in $allcells
do
  ./makecell $cell $inccap
done

cp $source_dir/$catal_name .
