#!/bin/bash

# Script which converts a vxlib vbe cell to a wsxlib one.
# The AREA is multiplied by 4.

old_height=72
new_height=80

cp -p ../vxlib013/$1.vbe .
sed 's|;| ;|' $1.vbe | \
awk -v "FS= " '/^ *CONSTANT  *area / {printf "  %1s %1s          %1s %1s %1s %1s %1s\n", $1,$2,$3,$4,$5,$6*4,$7 }
!/^ *CONSTANT  *area / {print}' | \
sed 's| ;|;|' > $$temp

mv -f $$temp $1.vbe

