#!/bin/bash
#
# script to create all cell views. Using Alliance version 20060218 and
# Magic version 7.4.8 with Magic compiled with the TCL option
#
if test $# -eq 0
then
  echo "# Usage ./makeallviews cell_name (without AP extension). Please supply cell_name."
  exit 1
fi
if test -f "$1.ap"
then
dir=$PWD

echo "#"
echo "# MAKING ALL VIEWS FOR CELL $1" 1>&2
echo "#"
echo "# Write wsclib013 CIF from Alliance"

full=0

source ../../../alliance/bin/env_wsc013
../../../alliance/bin/make_al $1
RDS_IN=cif
RDS_OUT=cif
rm -f $1.cif
s2r_any013 $1 >/dev/null
s2r -p $1 >/dev/null
../../../alliance/bin/touch_alliance_cif $1
cp $1.cif ../../../alliance/cif/wsclib013
../../../alliance/bin/grep_ref_boxes $1 ../../../magic/etc/wsclib/$1_wsc013.ref
grep '^4A' $1.cif > ../../../magic/etc/wsclib/$1_wsc013.ab

#echo "# Write wsclib013 GDS from Alliance"

#RDS_IN=gds
#RDS_OUT=gds
#rm -f $1.gds
#s2r_any013 $1 >/dev/null
#cp $1.gds ../../../alliance/gds/wsclib013

echo "# Write spice deck using wsc013 values"

../../../alliance/bin/any013_make_spice $1 wsclib
grep subckt $1.spi > ../../../magic/etc/wsclib/$1.subckt
cp $1.spi ../../../alliance/subckt/wsclib013

echo "# Write wsclib200 CIF from Alliance for Magic"

source ../../../alliance/bin/env_wsc200
RDS_IN=cif
RDS_OUT=cif
rm -f $1.cif
s2r_any013 $1 >/dev/null
s2r -p $1 >/dev/null
../../../alliance/bin/touch_alliance_cif $1
cp $1.cif ../../../alliance/cif/wsclib200
../../../alliance/bin/grep_ref_boxes $1 ../../../magic/etc/wsclib/$1_wsc200.ref
grep '^4A' $1.cif > ../../../magic/etc/wsclib/$1_wsc200.ab

../../../alliance/bin/make_magic_cif $1
cp $1.cif ../../../magic/cells/wsclib

if [ "$full" -eq 1 ]; then
echo "# Write wsclibp13_psc CIF from Alliance"

source ../../../alliance/bin/env_wscp13_psc
RDS_IN=cif
RDS_OUT=cif
rm -f $1.cif
s2r -i $1 >/dev/null
s2r -p $1 >/dev/null
../../../alliance/bin/touch_alliance_cif $1
cp $1.cif ../../../alliance/cif/wsclibp13_psc

#echo "# Write wsclibp13_psc GDS from Alliance"

#RDS_IN=gds
#RDS_OUT=gds
#rm -f $1.gds
#s2r -i $1 >/dev/null
#cp $1.gds ../../../alliance/gds/wsclibp13_psc

#echo "# Write wsclibp13_ll_psc GDS from Alliance"

#source ../../../alliance/bin/env_wscp13_ll_psc
#RDS_IN=gds
#RDS_OUT=gds
#rm -f $1.gds
#s2r -i $1 >/dev/null
#cp $1.gds ../../../alliance/gds/wsclibp13_ll_psc

#echo "# Write wsclibp13_hs_psc GDS from Alliance"

#source ../../../alliance/bin/env_wscp13_hs_psc
#RDS_IN=gds
#RDS_OUT=gds
#rm -f $1.gds
#s2r -i $1 >/dev/null
#cp $1.gds ../../../alliance/gds/wsclibp13_hs_psc
fi

rm -f $1.al
rm -f $1.spi
rm -f $1.cif
rm -f $1.gds

cd ../../../magic/cells/wsclib

#
# Script updated 31-MAR-06 to run with Magic compiled with TCL. The
# actual version of Magic being used is the 7.4.8 release.
#
# xhost + command needed for -noconsole option to be accepted
#
xhost + 1>/dev/null

echo
echo "# Read wsclib200 CIF into Magic"
magic -Tvsc200 -dnull -noconsole <<EOF  >/dev/null 2>&1
;cif read $1.cif
;load $1
;drc count total
;save
exit
EOF

echo "# Extract 0.13um SPI file from Magic"
magic -Tvsc013 -dnull -noconsole <<EOF >/dev/null 2>&1
;load $1
;box 0 0 1 1
;select more box pwell
;delete
;box 0 79 1 80
;select more box nwell
;delete
;select
;extract do capacitance
;extract do coupling
;extract do adjust
;extract do resistance
;extract all
;ext2spice -f spice3 -c 0.001 -r 1 -y 3 -d
;quit
EOF
#THE RC EXTRACTION DOESN'T WORK FOR NOW
#cp $1.cspice $1.spice
#../../../alliance/bin/spice2spi_013 $1 wsclib
#mv -f $1.spi $1.cspi
#magic -Tvsc013 -noconsole <<EOF
#;load $1
#;select
#;extresis tolerance 1000
#;extresis
#;ext2spice extresist on
#;exttospice -f spice3 -R -C -c 0.001 -r 1 -y 3 -d
#;quit
#EOF

echo "# Write wsclib200 CIF file from Magic"
magic -Tvsc200 -dnull -noconsole <<EOF >/dev/null 2>&1
;load $1
;cif write $1
;gds labels
;gds write $1
;quit
EOF

../../../alliance/bin/make_alliance_cif $1 ../../../alliance/cif/wsclib200/$1 ../../../magic/etc/wsclib/$1_wsc200.ref
cp $1.cif ../../../magic/cif/wsclib200
cp $1.gds ../../../magic/gds/wsclib200

if [ "$full" -eq 1 ]; then
echo "# Write vsclibp13_psc CIF and GDS files from Magic"
magic -Tvscp13 -dnull -noconsole <<EOF >/dev/null 2>&1
;load $1
;cif write $1
;gds labels
;gds write $1
;quit
EOF

../../../alliance/bin/make_alliance_cif $1 ../../../alliance/cif/wsclib013/$1 ../../../magic/etc/wsclib/$1_wsc013.ref
cp $1.cif ../../../magic/cif/wsclibp13_psc
cp $1.gds ../../../magic/gds/wsclibp13_psc

echo "# Write wsclibp13_ll_psc CIF and GDS files from Magic"
magic -Tvscp13 -dnull -noconsole <<EOF >/dev/null 2>&1
;load $1
;cif ostyle lambda=0.055um(vsclib_ll_psc)
;cif write $1
;gds labels
;gds write $1
;quit
EOF

../../../alliance/bin/make_alliance_cif $1 ../../../alliance/cif/wsclib013/$1 ../../../magic/etc/wsclib/$1_wsc013.ref
cp $1.cif ../../../magic/cif/wsclibp13_ll_psc
cp $1.gds ../../../magic/gds/wsclibp13_ll_psc

echo "# Write wsclibp13_hs_psc CIF and GDS files from Magic"
magic -Tvscp13 -dnull -noconsole <<EOF >/dev/null 2>&1
;load $1
;cif ostyle lambda=0.055um(vsclib_hs_psc)
;cif write $1
;gds labels
;gds write $1
;quit
EOF

../../../alliance/bin/make_alliance_cif $1 ../../../alliance/cif/wsclib013/$1 ../../../magic/etc/wsclib/$1_wsc013.ref
cp $1.cif ../../../magic/cif/wsclibp13_hs_psc
cp $1.gds ../../../magic/gds/wsclibp13_hs_psc
fi

echo "# Write wsclib013 CIF and GDS files from Magic"
magic -Tvsc013 -dnull -noconsole <<EOF >/dev/null 2>&1
;load $1
;cif ostyle lambda=0.055um(vsclib)
;cif write $1
;gds labels
;gds write $1
;quit
EOF

../../../alliance/bin/make_alliance_cif $1 ../../../alliance/cif/wsclib013/$1 ../../../magic/etc/wsclib/$1_wsc013.ref
cp $1.cif ../../../magic/cif/wsclib013
cp $1.gds ../../../magic/gds/wsclib013

echo
echo "# Convert Magic SPICE output to SPI subckt"
../../../alliance/bin/spice2spi_013 $1 wsclib
cp $1.spi ../../../magic/subckt/wsclib013
cd $dir
else
  echo "# Usage ./makeallviews cell_name (without AP extension). cell_name supplied does not exist."
  exit 1
fi
