
SHELL=/bin/bash

an2v0x05.vbe: ../../../alliance/makevbe/vsclib200/an2v0x05.bash
	echo "# Remake an2v0x05.vbe"
an2v0x1.vbe: ../../../alliance/makevbe/vsclib200/an2v0x1.bash
	echo "# Remake an2v0x1.vbe"
an2v0x2.vbe: ../../../alliance/makevbe/vsclib200/an2v0x2.bash
	echo "# Remake an2v0x2.vbe"
an2v0x3.vbe: ../../../alliance/makevbe/vsclib200/an2v0x3.bash
	echo "# Remake an2v0x3.vbe"
an2v0x4.vbe: ../../../alliance/makevbe/vsclib200/an2v0x4.bash
	echo "# Remake an2v0x4.vbe"
an2v0x6.vbe: ../../../alliance/makevbe/vsclib200/an2v0x6.bash
	echo "# Remake an2v0x6.vbe"
an2v0x8.vbe: ../../../alliance/makevbe/vsclib200/an2v0x8.bash
	echo "# Remake an2v0x8.vbe"
an2v2x2.vbe: ../../../alliance/makevbe/vsclib200/an2v2x2.bash
	echo "# Remake an2v2x2.vbe"
an2v4x1.vbe: ../../../alliance/makevbe/vsclib200/an2v4x1.bash
	echo "# Remake an2v4x1.vbe"
an2v4x2.vbe: ../../../alliance/makevbe/vsclib200/an2v4x2.bash
	echo "# Remake an2v4x2.vbe"
an2v4x4.vbe: ../../../alliance/makevbe/vsclib200/an2v4x4.bash
	echo "# Remake an2v4x4.vbe"
an2v4x8.vbe: ../../../alliance/makevbe/vsclib200/an2v4x8.bash
	echo "# Remake an2v4x8.vbe"
an3v0x05.vbe: ../../../alliance/makevbe/vsclib200/an3v0x05.bash
	echo "# Remake an3v0x05.vbe"
an3v0x1.vbe: ../../../alliance/makevbe/vsclib200/an3v0x1.bash
	echo "# Remake an3v0x1.vbe"
an3v0x2.vbe: ../../../alliance/makevbe/vsclib200/an3v0x2.bash
	echo "# Remake an3v0x2.vbe"
an3v0x4.vbe: ../../../alliance/makevbe/vsclib200/an3v0x4.bash
	echo "# Remake an3v0x4.vbe"
an3v4x1.vbe: ../../../alliance/makevbe/vsclib200/an3v4x1.bash
	echo "# Remake an3v4x1.vbe"
an3v4x2.vbe: ../../../alliance/makevbe/vsclib200/an3v4x2.bash
	echo "# Remake an3v4x2.vbe"
an3v6x05.vbe: ../../../alliance/makevbe/vsclib200/an3v6x05.bash
	echo "# Remake an3v6x05.vbe"
an4v0x05.vbe: ../../../alliance/makevbe/vsclib200/an4v0x05.bash
	echo "# Remake an4v0x05.vbe"
an4v0x1.vbe: ../../../alliance/makevbe/vsclib200/an4v0x1.bash
	echo "# Remake an4v0x1.vbe"
an4v0x2.vbe: ../../../alliance/makevbe/vsclib200/an4v0x2.bash
	echo "# Remake an4v0x2.vbe"
an4v0x4.vbe: ../../../alliance/makevbe/vsclib200/an4v0x4.bash
	echo "# Remake an4v0x4.vbe"
an4v4x1.vbe: ../../../alliance/makevbe/vsclib200/an4v4x1.bash
	echo "# Remake an4v4x1.vbe"
aoi112v0x05.vbe: ../../../alliance/makevbe/vsclib200/aoi112v0x05.bash
	echo "# Remake aoi112v0x05.vbe"
aoi211v0x05.vbe: ../../../alliance/makevbe/vsclib200/aoi211v0x05.bash
	echo "# Remake aoi211v0x05.vbe"
aoi211v0x1.vbe: ../../../alliance/makevbe/vsclib200/aoi211v0x1.bash
	echo "# Remake aoi211v0x1.vbe"
aoi211v0x2.vbe: ../../../alliance/makevbe/vsclib200/aoi211v0x2.bash
	echo "# Remake aoi211v0x2.vbe"
aoi211v5x05.vbe: ../../../alliance/makevbe/vsclib200/aoi211v5x05.bash
	echo "# Remake aoi211v5x05.vbe"
aoi21a2bv0x05.vbe: ../../../alliance/makevbe/vsclib200/aoi21a2bv0x05.bash
	echo "# Remake aoi21a2bv0x05.vbe"
aoi21a2bv5x05.vbe: ../../../alliance/makevbe/vsclib200/aoi21a2bv5x05.bash
	echo "# Remake aoi21a2bv5x05.vbe"
aoi21a2v0x05.vbe: ../../../alliance/makevbe/vsclib200/aoi21a2v0x05.bash
	echo "# Remake aoi21a2v0x05.vbe"
aoi21bv0x05.vbe: ../../../alliance/makevbe/vsclib200/aoi21bv0x05.bash
	echo "# Remake aoi21bv0x05.vbe"
aoi21v0x05.vbe: ../../../alliance/makevbe/vsclib200/aoi21v0x05.bash
	echo "# Remake aoi21v0x05.vbe"
aoi21v0x1.vbe: ../../../alliance/makevbe/vsclib200/aoi21v0x1.bash
	echo "# Remake aoi21v0x1.vbe"
aoi21v0x2.vbe: ../../../alliance/makevbe/vsclib200/aoi21v0x2.bash
	echo "# Remake aoi21v0x2.vbe"
aoi22v0x05.vbe: ../../../alliance/makevbe/vsclib200/aoi22v0x05.bash
	echo "# Remake aoi22v0x05.vbe"
aoi22v0x1.vbe: ../../../alliance/makevbe/vsclib200/aoi22v0x1.bash
	echo "# Remake aoi22v0x1.vbe"
aoi22v0x2.vbe: ../../../alliance/makevbe/vsclib200/aoi22v0x2.bash
	echo "# Remake aoi22v0x2.vbe"
aoi22v0x3.vbe: ../../../alliance/makevbe/vsclib200/aoi22v0x3.bash
	echo "# Remake aoi22v0x3.vbe"
aoi22v0x4.vbe: ../../../alliance/makevbe/vsclib200/aoi22v0x4.bash
	echo "# Remake aoi22v0x4.vbe"
aoi22v5x05.vbe: ../../../alliance/makevbe/vsclib200/aoi22v5x05.bash
	echo "# Remake aoi22v5x05.vbe"
aoi31v0x05.vbe: ../../../alliance/makevbe/vsclib200/aoi31v0x05.bash
	echo "# Remake aoi31v0x05.vbe"
aoi31v0x1.vbe: ../../../alliance/makevbe/vsclib200/aoi31v0x1.bash
	echo "# Remake aoi31v0x1.vbe"
aoi31v0x2.vbe: ../../../alliance/makevbe/vsclib200/aoi31v0x2.bash
	echo "# Remake aoi31v0x2.vbe"
aoi31v0x3.vbe: ../../../alliance/makevbe/vsclib200/aoi31v0x3.bash
	echo "# Remake aoi31v0x3.vbe"
aon21bv0x05.vbe: ../../../alliance/makevbe/vsclib200/aon21bv0x05.bash
	echo "# Remake aon21bv0x05.vbe"
aon21bv0x1.vbe: ../../../alliance/makevbe/vsclib200/aon21bv0x1.bash
	echo "# Remake aon21bv0x1.vbe"
aon21bv0x2.vbe: ../../../alliance/makevbe/vsclib200/aon21bv0x2.bash
	echo "# Remake aon21bv0x2.vbe"
aon21bv0x3.vbe: ../../../alliance/makevbe/vsclib200/aon21bv0x3.bash
	echo "# Remake aon21bv0x3.vbe"
aon21bv0x4.vbe: ../../../alliance/makevbe/vsclib200/aon21bv0x4.bash
	echo "# Remake aon21bv0x4.vbe"
aon21v0x05.vbe: ../../../alliance/makevbe/vsclib200/aon21v0x05.bash
	echo "# Remake aon21v0x05.vbe"
bf1v0x05.vbe: ../../../alliance/makevbe/vsclib200/bf1v0x05.bash
	echo "# Remake bf1v0x05.vbe"
bf1v0x12.vbe: ../../../alliance/makevbe/vsclib200/bf1v0x12.bash
	echo "# Remake bf1v0x12.vbe"
bf1v0x1.vbe: ../../../alliance/makevbe/vsclib200/bf1v0x1.bash
	echo "# Remake bf1v0x1.vbe"
bf1v0x2.vbe: ../../../alliance/makevbe/vsclib200/bf1v0x2.bash
	echo "# Remake bf1v0x2.vbe"
bf1v0x3.vbe: ../../../alliance/makevbe/vsclib200/bf1v0x3.bash
	echo "# Remake bf1v0x3.vbe"
bf1v0x4.vbe: ../../../alliance/makevbe/vsclib200/bf1v0x4.bash
	echo "# Remake bf1v0x4.vbe"
bf1v0x6.vbe: ../../../alliance/makevbe/vsclib200/bf1v0x6.bash
	echo "# Remake bf1v0x6.vbe"
bf1v0x8.vbe: ../../../alliance/makevbe/vsclib200/bf1v0x8.bash
	echo "# Remake bf1v0x8.vbe"
bf1v1x2.vbe: ../../../alliance/makevbe/vsclib200/bf1v1x2.bash
	echo "# Remake bf1v1x2.vbe"
bf1v2x1.vbe: ../../../alliance/makevbe/vsclib200/bf1v2x1.bash
	echo "# Remake bf1v2x1.vbe"
bf1v2x2.vbe: ../../../alliance/makevbe/vsclib200/bf1v2x2.bash
	echo "# Remake bf1v2x2.vbe"
bf1v2x3.vbe: ../../../alliance/makevbe/vsclib200/bf1v2x3.bash
	echo "# Remake bf1v2x3.vbe"
bf1v2x4.vbe: ../../../alliance/makevbe/vsclib200/bf1v2x4.bash
	echo "# Remake bf1v2x4.vbe"
bf1v2x6.vbe: ../../../alliance/makevbe/vsclib200/bf1v2x6.bash
	echo "# Remake bf1v2x6.vbe"
bf1v2x8.vbe: ../../../alliance/makevbe/vsclib200/bf1v2x8.bash
	echo "# Remake bf1v2x8.vbe"
bf1v4x1.vbe: ../../../alliance/makevbe/vsclib200/bf1v4x1.bash
	echo "# Remake bf1v4x1.vbe"
bf1v5x05.vbe: ../../../alliance/makevbe/vsclib200/bf1v5x05.bash
	echo "# Remake bf1v5x05.vbe"
bf1v5x1.vbe: ../../../alliance/makevbe/vsclib200/bf1v5x1.bash
	echo "# Remake bf1v5x1.vbe"
bf1v5x2.vbe: ../../../alliance/makevbe/vsclib200/bf1v5x2.bash
	echo "# Remake bf1v5x2.vbe"
bf1v5x4.vbe: ../../../alliance/makevbe/vsclib200/bf1v5x4.bash
	echo "# Remake bf1v5x4.vbe"
bf1v6x2.vbe: ../../../alliance/makevbe/vsclib200/bf1v6x2.bash
	echo "# Remake bf1v6x2.vbe"
bf1v8x4.vbe: ../../../alliance/makevbe/vsclib200/bf1v8x4.bash
	echo "# Remake bf1v8x4.vbe"
bsi2v2x1.vbe: ../../../alliance/makevbe/vsclib200/bsi2v2x1.bash
	echo "# Remake bsi2v2x1.vbe"
cgi2abv0x05.vbe: ../../../alliance/makevbe/vsclib200/cgi2abv0x05.bash
	echo "# Remake cgi2abv0x05.vbe"
cgi2abv0x1.vbe: ../../../alliance/makevbe/vsclib200/cgi2abv0x1.bash
	echo "# Remake cgi2abv0x1.vbe"
cgi2abv0x2.vbe: ../../../alliance/makevbe/vsclib200/cgi2abv0x2.bash
	echo "# Remake cgi2abv0x2.vbe"
cgi2bv0x05.vbe: ../../../alliance/makevbe/vsclib200/cgi2bv0x05.bash
	echo "# Remake cgi2bv0x05.vbe"
cgi2bv0x1.vbe: ../../../alliance/makevbe/vsclib200/cgi2bv0x1.bash
	echo "# Remake cgi2bv0x1.vbe"
cgi2bv0x2.vbe: ../../../alliance/makevbe/vsclib200/cgi2bv0x2.bash
	echo "# Remake cgi2bv0x2.vbe"
cgi2bv0x3.vbe: ../../../alliance/makevbe/vsclib200/cgi2bv0x3.bash
	echo "# Remake cgi2bv0x3.vbe"
cgi2cv0x05.vbe: ../../../alliance/makevbe/vsclib200/cgi2cv0x05.bash
	echo "# Remake cgi2cv0x05.vbe"
cgi2cv0x1.vbe: ../../../alliance/makevbe/vsclib200/cgi2cv0x1.bash
	echo "# Remake cgi2cv0x1.vbe"
cgi2cv0x2.vbe: ../../../alliance/makevbe/vsclib200/cgi2cv0x2.bash
	echo "# Remake cgi2cv0x2.vbe"
cgi2cv0x3.vbe: ../../../alliance/makevbe/vsclib200/cgi2cv0x3.bash
	echo "# Remake cgi2cv0x3.vbe"
cgi2v0x05.vbe: ../../../alliance/makevbe/vsclib200/cgi2v0x05.bash
	echo "# Remake cgi2v0x05.vbe"
cgi2v0x1.vbe: ../../../alliance/makevbe/vsclib200/cgi2v0x1.bash
	echo "# Remake cgi2v0x1.vbe"
cgi2v0x2.vbe: ../../../alliance/makevbe/vsclib200/cgi2v0x2.bash
	echo "# Remake cgi2v0x2.vbe"
cgi2v0x3.vbe: ../../../alliance/makevbe/vsclib200/cgi2v0x3.bash
	echo "# Remake cgi2v0x3.vbe"
dfnt1v0x2.vbe: ../../../alliance/makevbe/vsclib200/dfnt1v0x2.bash
	echo "# Remake dfnt1v0x2.vbe"
dly1v0x05.vbe: ../../../alliance/makevbe/vsclib200/dly1v0x05.bash
	echo "# Remake dly1v0x05.vbe"
dly2v0x05.vbe: ../../../alliance/makevbe/vsclib200/dly2v0x05.bash
	echo "# Remake dly2v0x05.vbe"
dly2v0x1.vbe: ../../../alliance/makevbe/vsclib200/dly2v0x1.bash
	echo "# Remake dly2v0x1.vbe"
ha2v0x2.vbe: ../../../alliance/makevbe/vsclib200/ha2v0x2.bash
	echo "# Remake ha2v0x2.vbe"
iv1v0x05.vbe: ../../../alliance/makevbe/vsclib200/iv1v0x05.bash
	echo "# Remake iv1v0x05.vbe"
iv1v0x12.vbe: ../../../alliance/makevbe/vsclib200/iv1v0x12.bash
	echo "# Remake iv1v0x12.vbe"
iv1v0x1.vbe: ../../../alliance/makevbe/vsclib200/iv1v0x1.bash
	echo "# Remake iv1v0x1.vbe"
iv1v0x2.vbe: ../../../alliance/makevbe/vsclib200/iv1v0x2.bash
	echo "# Remake iv1v0x2.vbe"
iv1v0x3.vbe: ../../../alliance/makevbe/vsclib200/iv1v0x3.bash
	echo "# Remake iv1v0x3.vbe"
iv1v0x4.vbe: ../../../alliance/makevbe/vsclib200/iv1v0x4.bash
	echo "# Remake iv1v0x4.vbe"
iv1v0x6.vbe: ../../../alliance/makevbe/vsclib200/iv1v0x6.bash
	echo "# Remake iv1v0x6.vbe"
iv1v0x8.vbe: ../../../alliance/makevbe/vsclib200/iv1v0x8.bash
	echo "# Remake iv1v0x8.vbe"
iv1v1x05.vbe: ../../../alliance/makevbe/vsclib200/iv1v1x05.bash
	echo "# Remake iv1v1x05.vbe"
iv1v1x1.vbe: ../../../alliance/makevbe/vsclib200/iv1v1x1.bash
	echo "# Remake iv1v1x1.vbe"
iv1v1x2.vbe: ../../../alliance/makevbe/vsclib200/iv1v1x2.bash
	echo "# Remake iv1v1x2.vbe"
iv1v1x4.vbe: ../../../alliance/makevbe/vsclib200/iv1v1x4.bash
	echo "# Remake iv1v1x4.vbe"
iv1v1x8.vbe: ../../../alliance/makevbe/vsclib200/iv1v1x8.bash
	echo "# Remake iv1v1x8.vbe"
iv1v2x2.vbe: ../../../alliance/makevbe/vsclib200/iv1v2x2.bash
	echo "# Remake iv1v2x2.vbe"
iv1v3x1.vbe: ../../../alliance/makevbe/vsclib200/iv1v3x1.bash
	echo "# Remake iv1v3x1.vbe"
iv1v3x3.vbe: ../../../alliance/makevbe/vsclib200/iv1v3x3.bash
	echo "# Remake iv1v3x3.vbe"
iv1v3x6.vbe: ../../../alliance/makevbe/vsclib200/iv1v3x6.bash
	echo "# Remake iv1v3x6.vbe"
iv1v4x12.vbe: ../../../alliance/makevbe/vsclib200/iv1v4x12.bash
	echo "# Remake iv1v4x12.vbe"
iv1v4x1.vbe: ../../../alliance/makevbe/vsclib200/iv1v4x1.bash
	echo "# Remake iv1v4x1.vbe"
iv1v4x2.vbe: ../../../alliance/makevbe/vsclib200/iv1v4x2.bash
	echo "# Remake iv1v4x2.vbe"
iv1v4x3.vbe: ../../../alliance/makevbe/vsclib200/iv1v4x3.bash
	echo "# Remake iv1v4x3.vbe"
iv1v4x4.vbe: ../../../alliance/makevbe/vsclib200/iv1v4x4.bash
	echo "# Remake iv1v4x4.vbe"
iv1v4x6.vbe: ../../../alliance/makevbe/vsclib200/iv1v4x6.bash
	echo "# Remake iv1v4x6.vbe"
iv1v4x8.vbe: ../../../alliance/makevbe/vsclib200/iv1v4x8.bash
	echo "# Remake iv1v4x8.vbe"
iv1v5x12.vbe: ../../../alliance/makevbe/vsclib200/iv1v5x12.bash
	echo "# Remake iv1v5x12.vbe"
iv1v5x1.vbe: ../../../alliance/makevbe/vsclib200/iv1v5x1.bash
	echo "# Remake iv1v5x1.vbe"
iv1v5x2.vbe: ../../../alliance/makevbe/vsclib200/iv1v5x2.bash
	echo "# Remake iv1v5x2.vbe"
iv1v5x3.vbe: ../../../alliance/makevbe/vsclib200/iv1v5x3.bash
	echo "# Remake iv1v5x3.vbe"
iv1v5x4.vbe: ../../../alliance/makevbe/vsclib200/iv1v5x4.bash
	echo "# Remake iv1v5x4.vbe"
iv1v5x6.vbe: ../../../alliance/makevbe/vsclib200/iv1v5x6.bash
	echo "# Remake iv1v5x6.vbe"
iv1v5x8.vbe: ../../../alliance/makevbe/vsclib200/iv1v5x8.bash
	echo "# Remake iv1v5x8.vbe"
iv1v6x1.vbe: ../../../alliance/makevbe/vsclib200/iv1v6x1.bash
	echo "# Remake iv1v6x1.vbe"
iv1v6x2.vbe: ../../../alliance/makevbe/vsclib200/iv1v6x2.bash
	echo "# Remake iv1v6x2.vbe"
iv1v7x1.vbe: ../../../alliance/makevbe/vsclib200/iv1v7x1.bash
	echo "# Remake iv1v7x1.vbe"
iv1v8x1.vbe: ../../../alliance/makevbe/vsclib200/iv1v8x1.bash
	echo "# Remake iv1v8x1.vbe"
mxi2v0x05.vbe: ../../../alliance/makevbe/vsclib200/mxi2v0x05.bash
	echo "# Remake mxi2v0x05.vbe"
mxi2v0x1.vbe: ../../../alliance/makevbe/vsclib200/mxi2v0x1.bash
	echo "# Remake mxi2v0x1.vbe"
mxi2v0x2.vbe: ../../../alliance/makevbe/vsclib200/mxi2v0x2.bash
	echo "# Remake mxi2v0x2.vbe"
mxi2v2x05.vbe: ../../../alliance/makevbe/vsclib200/mxi2v2x05.bash
	echo "# Remake mxi2v2x05.vbe"
mxi2v2x1.vbe: ../../../alliance/makevbe/vsclib200/mxi2v2x1.bash
	echo "# Remake mxi2v2x1.vbe"
mxi2v2x2.vbe: ../../../alliance/makevbe/vsclib200/mxi2v2x2.bash
	echo "# Remake mxi2v2x2.vbe"
mxi2v2x3.vbe: ../../../alliance/makevbe/vsclib200/mxi2v2x3.bash
	echo "# Remake mxi2v2x3.vbe"
mxi2v2x4.vbe: ../../../alliance/makevbe/vsclib200/mxi2v2x4.bash
	echo "# Remake mxi2v2x4.vbe"
mxn2v0x05.vbe: ../../../alliance/makevbe/vsclib200/mxn2v0x05.bash
	echo "# Remake mxn2v0x05.vbe"
mxn2v0x1.vbe: ../../../alliance/makevbe/vsclib200/mxn2v0x1.bash
	echo "# Remake mxn2v0x1.vbe"
mxn2v2x1.vbe: ../../../alliance/makevbe/vsclib200/mxn2v2x1.bash
	echo "# Remake mxn2v2x1.vbe"
nd2abv0x05.vbe: ../../../alliance/makevbe/vsclib200/nd2abv0x05.bash
	echo "# Remake nd2abv0x05.vbe"
nd2abv0x1.vbe: ../../../alliance/makevbe/vsclib200/nd2abv0x1.bash
	echo "# Remake nd2abv0x1.vbe"
nd2abv0x2.vbe: ../../../alliance/makevbe/vsclib200/nd2abv0x2.bash
	echo "# Remake nd2abv0x2.vbe"
nd2abv0x3.vbe: ../../../alliance/makevbe/vsclib200/nd2abv0x3.bash
	echo "# Remake nd2abv0x3.vbe"
nd2abv0x4.vbe: ../../../alliance/makevbe/vsclib200/nd2abv0x4.bash
	echo "# Remake nd2abv0x4.vbe"
nd2av0x05.vbe: ../../../alliance/makevbe/vsclib200/nd2av0x05.bash
	echo "# Remake nd2av0x05.vbe"
nd2av0x1.vbe: ../../../alliance/makevbe/vsclib200/nd2av0x1.bash
	echo "# Remake nd2av0x1.vbe"
nd2av0x2.vbe: ../../../alliance/makevbe/vsclib200/nd2av0x2.bash
	echo "# Remake nd2av0x2.vbe"
nd2av0x3.vbe: ../../../alliance/makevbe/vsclib200/nd2av0x3.bash
	echo "# Remake nd2av0x3.vbe"
nd2av0x4.vbe: ../../../alliance/makevbe/vsclib200/nd2av0x4.bash
	echo "# Remake nd2av0x4.vbe"
nd2av0x6.vbe: ../../../alliance/makevbe/vsclib200/nd2av0x6.bash
	echo "# Remake nd2av0x6.vbe"
nd2av0x8.vbe: ../../../alliance/makevbe/vsclib200/nd2av0x8.bash
	echo "# Remake nd2av0x8.vbe"
nd2v0x05.vbe: ../../../alliance/makevbe/vsclib200/nd2v0x05.bash
	echo "# Remake nd2v0x05.vbe"
nd2v0x1.vbe: ../../../alliance/makevbe/vsclib200/nd2v0x1.bash
	echo "# Remake nd2v0x1.vbe"
nd2v0x2.vbe: ../../../alliance/makevbe/vsclib200/nd2v0x2.bash
	echo "# Remake nd2v0x2.vbe"
nd2v0x3.vbe: ../../../alliance/makevbe/vsclib200/nd2v0x3.bash
	echo "# Remake nd2v0x3.vbe"
nd2v0x4.vbe: ../../../alliance/makevbe/vsclib200/nd2v0x4.bash
	echo "# Remake nd2v0x4.vbe"
nd2v0x6.vbe: ../../../alliance/makevbe/vsclib200/nd2v0x6.bash
	echo "# Remake nd2v0x6.vbe"
nd2v0x8.vbe: ../../../alliance/makevbe/vsclib200/nd2v0x8.bash
	echo "# Remake nd2v0x8.vbe"
nd2v3x05.vbe: ../../../alliance/makevbe/vsclib200/nd2v3x05.bash
	echo "# Remake nd2v3x05.vbe"
nd2v3x1.vbe: ../../../alliance/makevbe/vsclib200/nd2v3x1.bash
	echo "# Remake nd2v3x1.vbe"
nd2v3x2.vbe: ../../../alliance/makevbe/vsclib200/nd2v3x2.bash
	echo "# Remake nd2v3x2.vbe"
nd2v3x3.vbe: ../../../alliance/makevbe/vsclib200/nd2v3x3.bash
	echo "# Remake nd2v3x3.vbe"
nd2v3x4.vbe: ../../../alliance/makevbe/vsclib200/nd2v3x4.bash
	echo "# Remake nd2v3x4.vbe"
nd2v4x1.vbe: ../../../alliance/makevbe/vsclib200/nd2v4x1.bash
	echo "# Remake nd2v4x1.vbe"
nd2v4x2.vbe: ../../../alliance/makevbe/vsclib200/nd2v4x2.bash
	echo "# Remake nd2v4x2.vbe"
nd2v4x3.vbe: ../../../alliance/makevbe/vsclib200/nd2v4x3.bash
	echo "# Remake nd2v4x3.vbe"
nd2v4x4.vbe: ../../../alliance/makevbe/vsclib200/nd2v4x4.bash
	echo "# Remake nd2v4x4.vbe"
nd2v4x6.vbe: ../../../alliance/makevbe/vsclib200/nd2v4x6.bash
	echo "# Remake nd2v4x6.vbe"
nd2v4x8.vbe: ../../../alliance/makevbe/vsclib200/nd2v4x8.bash
	echo "# Remake nd2v4x8.vbe"
nd2v5x05.vbe: ../../../alliance/makevbe/vsclib200/nd2v5x05.bash
	echo "# Remake nd2v5x05.vbe"
nd2v5x1.vbe: ../../../alliance/makevbe/vsclib200/nd2v5x1.bash
	echo "# Remake nd2v5x1.vbe"
nd2v5x2.vbe: ../../../alliance/makevbe/vsclib200/nd2v5x2.bash
	echo "# Remake nd2v5x2.vbe"
nd2v5x3.vbe: ../../../alliance/makevbe/vsclib200/nd2v5x3.bash
	echo "# Remake nd2v5x3.vbe"
nd2v5x4.vbe: ../../../alliance/makevbe/vsclib200/nd2v5x4.bash
	echo "# Remake nd2v5x4.vbe"
nd2v5x6.vbe: ../../../alliance/makevbe/vsclib200/nd2v5x6.bash
	echo "# Remake nd2v5x6.vbe"
nd2v5x8.vbe: ../../../alliance/makevbe/vsclib200/nd2v5x8.bash
	echo "# Remake nd2v5x8.vbe"
nd2v6x3.vbe: ../../../alliance/makevbe/vsclib200/nd2v6x3.bash
	echo "# Remake nd2v6x3.vbe"
nd3abv0x05.vbe: ../../../alliance/makevbe/vsclib200/nd3abv0x05.bash
	echo "# Remake nd3abv0x05.vbe"
nd3av0x05.vbe: ../../../alliance/makevbe/vsclib200/nd3av0x05.bash
	echo "# Remake nd3av0x05.vbe"
nd3v0x05.vbe: ../../../alliance/makevbe/vsclib200/nd3v0x05.bash
	echo "# Remake nd3v0x05.vbe"
nd3v0x1.vbe: ../../../alliance/makevbe/vsclib200/nd3v0x1.bash
	echo "# Remake nd3v0x1.vbe"
nd3v0x2.vbe: ../../../alliance/makevbe/vsclib200/nd3v0x2.bash
	echo "# Remake nd3v0x2.vbe"
nd3v0x3.vbe: ../../../alliance/makevbe/vsclib200/nd3v0x3.bash
	echo "# Remake nd3v0x3.vbe"
nd3v0x4.vbe: ../../../alliance/makevbe/vsclib200/nd3v0x4.bash
	echo "# Remake nd3v0x4.vbe"
nd3v0x6.vbe: ../../../alliance/makevbe/vsclib200/nd3v0x6.bash
	echo "# Remake nd3v0x6.vbe"
nd3v5x2.vbe: ../../../alliance/makevbe/vsclib200/nd3v5x2.bash
	echo "# Remake nd3v5x2.vbe"
nd3v5x3.vbe: ../../../alliance/makevbe/vsclib200/nd3v5x3.bash
	echo "# Remake nd3v5x3.vbe"
nd3v5x4.vbe: ../../../alliance/makevbe/vsclib200/nd3v5x4.bash
	echo "# Remake nd3v5x4.vbe"
nd3v5x6.vbe: ../../../alliance/makevbe/vsclib200/nd3v5x6.bash
	echo "# Remake nd3v5x6.vbe"
nd3v6x6.vbe: ../../../alliance/makevbe/vsclib200/nd3v6x6.bash
	echo "# Remake nd3v6x6.vbe"
nd4v0x05.vbe: ../../../alliance/makevbe/vsclib200/nd4v0x05.bash
	echo "# Remake nd4v0x05.vbe"
nd4v0x1.vbe: ../../../alliance/makevbe/vsclib200/nd4v0x1.bash
	echo "# Remake nd4v0x1.vbe"
nd4v0x2.vbe: ../../../alliance/makevbe/vsclib200/nd4v0x2.bash
	echo "# Remake nd4v0x2.vbe"
nd4v0x3.vbe: ../../../alliance/makevbe/vsclib200/nd4v0x3.bash
	echo "# Remake nd4v0x3.vbe"
nr2av0x1.vbe: ../../../alliance/makevbe/vsclib200/nr2av0x1.bash
	echo "# Remake nr2av0x1.vbe"
nr2av0x2.vbe: ../../../alliance/makevbe/vsclib200/nr2av0x2.bash
	echo "# Remake nr2av0x2.vbe"
nr2av0x3.vbe: ../../../alliance/makevbe/vsclib200/nr2av0x3.bash
	echo "# Remake nr2av0x3.vbe"
nr2av0x4.vbe: ../../../alliance/makevbe/vsclib200/nr2av0x4.bash
	echo "# Remake nr2av0x4.vbe"
nr2av0x6.vbe: ../../../alliance/makevbe/vsclib200/nr2av0x6.bash
	echo "# Remake nr2av0x6.vbe"
nr2av1x05.vbe: ../../../alliance/makevbe/vsclib200/nr2av1x05.bash
	echo "# Remake nr2av1x05.vbe"
nr2v0x05.vbe: ../../../alliance/makevbe/vsclib200/nr2v0x05.bash
	echo "# Remake nr2v0x05.vbe"
nr2v0x1.vbe: ../../../alliance/makevbe/vsclib200/nr2v0x1.bash
	echo "# Remake nr2v0x1.vbe"
nr2v0x2.vbe: ../../../alliance/makevbe/vsclib200/nr2v0x2.bash
	echo "# Remake nr2v0x2.vbe"
nr2v0x3.vbe: ../../../alliance/makevbe/vsclib200/nr2v0x3.bash
	echo "# Remake nr2v0x3.vbe"
nr2v0x4.vbe: ../../../alliance/makevbe/vsclib200/nr2v0x4.bash
	echo "# Remake nr2v0x4.vbe"
nr2v0x6.vbe: ../../../alliance/makevbe/vsclib200/nr2v0x6.bash
	echo "# Remake nr2v0x6.vbe"
nr2v0x8.vbe: ../../../alliance/makevbe/vsclib200/nr2v0x8.bash
	echo "# Remake nr2v0x8.vbe"
nr2v1x05.vbe: ../../../alliance/makevbe/vsclib200/nr2v1x05.bash
	echo "# Remake nr2v1x05.vbe"
nr2v1x1.vbe: ../../../alliance/makevbe/vsclib200/nr2v1x1.bash
	echo "# Remake nr2v1x1.vbe"
nr2v1x2.vbe: ../../../alliance/makevbe/vsclib200/nr2v1x2.bash
	echo "# Remake nr2v1x2.vbe"
nr2v1x3.vbe: ../../../alliance/makevbe/vsclib200/nr2v1x3.bash
	echo "# Remake nr2v1x3.vbe"
nr2v1x4.vbe: ../../../alliance/makevbe/vsclib200/nr2v1x4.bash
	echo "# Remake nr2v1x4.vbe"
nr2v1x6.vbe: ../../../alliance/makevbe/vsclib200/nr2v1x6.bash
	echo "# Remake nr2v1x6.vbe"
nr2v1x8.vbe: ../../../alliance/makevbe/vsclib200/nr2v1x8.bash
	echo "# Remake nr2v1x8.vbe"
nr3abv0x05.vbe: ../../../alliance/makevbe/vsclib200/nr3abv0x05.bash
	echo "# Remake nr3abv0x05.vbe"
nr3av0x05.vbe: ../../../alliance/makevbe/vsclib200/nr3av0x05.bash
	echo "# Remake nr3av0x05.vbe"
nr3v0x05.vbe: ../../../alliance/makevbe/vsclib200/nr3v0x05.bash
	echo "# Remake nr3v0x05.vbe"
nr3v0x1.vbe: ../../../alliance/makevbe/vsclib200/nr3v0x1.bash
	echo "# Remake nr3v0x1.vbe"
nr3v0x2.vbe: ../../../alliance/makevbe/vsclib200/nr3v0x2.bash
	echo "# Remake nr3v0x2.vbe"
nr3v0x3.vbe: ../../../alliance/makevbe/vsclib200/nr3v0x3.bash
	echo "# Remake nr3v0x3.vbe"
nr3v0x4.vbe: ../../../alliance/makevbe/vsclib200/nr3v0x4.bash
	echo "# Remake nr3v0x4.vbe"
nr3v1x05.vbe: ../../../alliance/makevbe/vsclib200/nr3v1x05.bash
	echo "# Remake nr3v1x05.vbe"
nr4v0x1.vbe: ../../../alliance/makevbe/vsclib200/nr4v0x1.bash
	echo "# Remake nr4v0x1.vbe"
nr4v0x2.vbe: ../../../alliance/makevbe/vsclib200/nr4v0x2.bash
	echo "# Remake nr4v0x2.vbe"
nr4v1x05.vbe: ../../../alliance/makevbe/vsclib200/nr4v1x05.bash
	echo "# Remake nr4v1x05.vbe"
oai211v0x05.vbe: ../../../alliance/makevbe/vsclib200/oai211v0x05.bash
	echo "# Remake oai211v0x05.vbe"
oai211v0x1.vbe: ../../../alliance/makevbe/vsclib200/oai211v0x1.bash
	echo "# Remake oai211v0x1.vbe"
oai21a2bv0x05.vbe: ../../../alliance/makevbe/vsclib200/oai21a2bv0x05.bash
	echo "# Remake oai21a2bv0x05.vbe"
oai21a2v0x05.vbe: ../../../alliance/makevbe/vsclib200/oai21a2v0x05.bash
	echo "# Remake oai21a2v0x05.vbe"
oai21a2v0x1.vbe: ../../../alliance/makevbe/vsclib200/oai21a2v0x1.bash
	echo "# Remake oai21a2v0x1.vbe"
oai21bv0x05.vbe: ../../../alliance/makevbe/vsclib200/oai21bv0x05.bash
	echo "# Remake oai21bv0x05.vbe"
oai21v0x05.vbe: ../../../alliance/makevbe/vsclib200/oai21v0x05.bash
	echo "# Remake oai21v0x05.vbe"
oai21v0x1.vbe: ../../../alliance/makevbe/vsclib200/oai21v0x1.bash
	echo "# Remake oai21v0x1.vbe"
oai21v0x2.vbe: ../../../alliance/makevbe/vsclib200/oai21v0x2.bash
	echo "# Remake oai21v0x2.vbe"
oai21v0x3.vbe: ../../../alliance/makevbe/vsclib200/oai21v0x3.bash
	echo "# Remake oai21v0x3.vbe"
oai21v0x4.vbe: ../../../alliance/makevbe/vsclib200/oai21v0x4.bash
	echo "# Remake oai21v0x4.vbe"
oai21v0x6.vbe: ../../../alliance/makevbe/vsclib200/oai21v0x6.bash
	echo "# Remake oai21v0x6.vbe"
oai21v0x8.vbe: ../../../alliance/makevbe/vsclib200/oai21v0x8.bash
	echo "# Remake oai21v0x8.vbe"
oai22v0x05.vbe: ../../../alliance/makevbe/vsclib200/oai22v0x05.bash
	echo "# Remake oai22v0x05.vbe"
oai22v0x1.vbe: ../../../alliance/makevbe/vsclib200/oai22v0x1.bash
	echo "# Remake oai22v0x1.vbe"
oai22v0x2.vbe: ../../../alliance/makevbe/vsclib200/oai22v0x2.bash
	echo "# Remake oai22v0x2.vbe"
oai23av0x05.vbe: ../../../alliance/makevbe/vsclib200/oai23av0x05.bash
	echo "# Remake oai23av0x05.vbe"
oai31v0x05.vbe: ../../../alliance/makevbe/vsclib200/oai31v0x05.bash
	echo "# Remake oai31v0x05.vbe"
oai31v0x1.vbe: ../../../alliance/makevbe/vsclib200/oai31v0x1.bash
	echo "# Remake oai31v0x1.vbe"
oai31v0x2.vbe: ../../../alliance/makevbe/vsclib200/oai31v0x2.bash
	echo "# Remake oai31v0x2.vbe"
oan21bv0x05.vbe: ../../../alliance/makevbe/vsclib200/oan21bv0x05.bash
	echo "# Remake oan21bv0x05.vbe"
oan21v0x05.vbe: ../../../alliance/makevbe/vsclib200/oan21v0x05.bash
	echo "# Remake oan21v0x05.vbe"
or2v0x05.vbe: ../../../alliance/makevbe/vsclib200/or2v0x05.bash
	echo "# Remake or2v0x05.vbe"
or2v0x1.vbe: ../../../alliance/makevbe/vsclib200/or2v0x1.bash
	echo "# Remake or2v0x1.vbe"
or2v0x2.vbe: ../../../alliance/makevbe/vsclib200/or2v0x2.bash
	echo "# Remake or2v0x2.vbe"
or2v0x3.vbe: ../../../alliance/makevbe/vsclib200/or2v0x3.bash
	echo "# Remake or2v0x3.vbe"
or2v0x4.vbe: ../../../alliance/makevbe/vsclib200/or2v0x4.bash
	echo "# Remake or2v0x4.vbe"
or2v0x8.vbe: ../../../alliance/makevbe/vsclib200/or2v0x8.bash
	echo "# Remake or2v0x8.vbe"
or2v4x1.vbe: ../../../alliance/makevbe/vsclib200/or2v4x1.bash
	echo "# Remake or2v4x1.vbe"
or2v7x2.vbe: ../../../alliance/makevbe/vsclib200/or2v7x2.bash
	echo "# Remake or2v7x2.vbe"
or3v0x05.vbe: ../../../alliance/makevbe/vsclib200/or3v0x05.bash
	echo "# Remake or3v0x05.vbe"
or3v0x1.vbe: ../../../alliance/makevbe/vsclib200/or3v0x1.bash
	echo "# Remake or3v0x1.vbe"
or3v0x2.vbe: ../../../alliance/makevbe/vsclib200/or3v0x2.bash
	echo "# Remake or3v0x2.vbe"
or3v0x3.vbe: ../../../alliance/makevbe/vsclib200/or3v0x3.bash
	echo "# Remake or3v0x3.vbe"
or3v0x4.vbe: ../../../alliance/makevbe/vsclib200/or3v0x4.bash
	echo "# Remake or3v0x4.vbe"
or3v3x2.vbe: ../../../alliance/makevbe/vsclib200/or3v3x2.bash
	echo "# Remake or3v3x2.vbe"
or3v4x05.vbe: ../../../alliance/makevbe/vsclib200/or3v4x05.bash
	echo "# Remake or3v4x05.vbe"
or4v0x05.vbe: ../../../alliance/makevbe/vsclib200/or4v0x05.bash
	echo "# Remake or4v0x05.vbe"
or4v0x1.vbe: ../../../alliance/makevbe/vsclib200/or4v0x1.bash
	echo "# Remake or4v0x1.vbe"
or4v0x2.vbe: ../../../alliance/makevbe/vsclib200/or4v0x2.bash
	echo "# Remake or4v0x2.vbe"
or4v0x3.vbe: ../../../alliance/makevbe/vsclib200/or4v0x3.bash
	echo "# Remake or4v0x3.vbe"
or4v3x2.vbe: ../../../alliance/makevbe/vsclib200/or4v3x2.bash
	echo "# Remake or4v3x2.vbe"
or4v4x05.vbe: ../../../alliance/makevbe/vsclib200/or4v4x05.bash
	echo "# Remake or4v4x05.vbe"
rowend_x0.vbe: ../../../alliance/makevbe/vsclib200/rowend_x0.bash
	echo "# Remake rowend_x0.vbe"
tie_x0.vbe: ../../../alliance/makevbe/vsclib200/tie_x0.bash
	echo "# Remake tie_x0.vbe"
vddtie.vbe: ../../../alliance/makevbe/vsclib200/vddtie.bash
	echo "# Remake vddtie.vbe"
vfeed1.vbe: ../../../alliance/makevbe/vsclib200/vfeed1.bash
	echo "# Remake vfeed1.vbe"
vfeed2.vbe: ../../../alliance/makevbe/vsclib200/vfeed2.bash
	echo "# Remake vfeed2.vbe"
vfeed3.vbe: ../../../alliance/makevbe/vsclib200/vfeed3.bash
	echo "# Remake vfeed3.vbe"
vfeed4.vbe: ../../../alliance/makevbe/vsclib200/vfeed4.bash
	echo "# Remake vfeed4.vbe"
vfeed5.vbe: ../../../alliance/makevbe/vsclib200/vfeed5.bash
	echo "# Remake vfeed5.vbe"
vfeed6.vbe: ../../../alliance/makevbe/vsclib200/vfeed6.bash
	echo "# Remake vfeed6.vbe"
vfeed7.vbe: ../../../alliance/makevbe/vsclib200/vfeed7.bash
	echo "# Remake vfeed7.vbe"
vfeed8.vbe: ../../../alliance/makevbe/vsclib200/vfeed8.bash
	echo "# Remake vfeed8.vbe"
vsstie.vbe: ../../../alliance/makevbe/vsclib200/vsstie.bash
	echo "# Remake vsstie.vbe"
xaoi21v0x05.vbe: ../../../alliance/makevbe/vsclib200/xaoi21v0x05.bash
	echo "# Remake xaoi21v0x05.vbe"
xaoi21v0x1.vbe: ../../../alliance/makevbe/vsclib200/xaoi21v0x1.bash
	echo "# Remake xaoi21v0x1.vbe"
xaoi21v0x2.vbe: ../../../alliance/makevbe/vsclib200/xaoi21v0x2.bash
	echo "# Remake xaoi21v0x2.vbe"
xaon21v0x05.vbe: ../../../alliance/makevbe/vsclib200/xaon21v0x05.bash
	echo "# Remake xaon21v0x05.vbe"
xaon21v0x1.vbe: ../../../alliance/makevbe/vsclib200/xaon21v0x1.bash
	echo "# Remake xaon21v0x1.vbe"
xaon21v0x2.vbe: ../../../alliance/makevbe/vsclib200/xaon21v0x2.bash
	echo "# Remake xaon21v0x2.vbe"
xaon21v0x3.vbe: ../../../alliance/makevbe/vsclib200/xaon21v0x3.bash
	echo "# Remake xaon21v0x3.vbe"
xnai21v0x05.vbe: ../../../alliance/makevbe/vsclib200/xnai21v0x05.bash
	echo "# Remake xnai21v0x05.vbe"
xnai21v1x05.vbe: ../../../alliance/makevbe/vsclib200/xnai21v1x05.bash
	echo "# Remake xnai21v1x05.vbe"
xnai21v2x05.vbe: ../../../alliance/makevbe/vsclib200/xnai21v2x05.bash
	echo "# Remake xnai21v2x05.vbe"
xnr2v0x05.vbe: ../../../alliance/makevbe/vsclib200/xnr2v0x05.bash
	echo "# Remake xnr2v0x05.vbe"
xnr2v0x1.vbe: ../../../alliance/makevbe/vsclib200/xnr2v0x1.bash
	echo "# Remake xnr2v0x1.vbe"
xnr2v0x2.vbe: ../../../alliance/makevbe/vsclib200/xnr2v0x2.bash
	echo "# Remake xnr2v0x2.vbe"
xnr2v0x3.vbe: ../../../alliance/makevbe/vsclib200/xnr2v0x3.bash
	echo "# Remake xnr2v0x3.vbe"
xnr2v0x4.vbe: ../../../alliance/makevbe/vsclib200/xnr2v0x4.bash
	echo "# Remake xnr2v0x4.vbe"
xnr2v6x1.vbe: ../../../alliance/makevbe/vsclib200/xnr2v6x1.bash
	echo "# Remake xnr2v6x1.vbe"
xnr2v8x05.vbe: ../../../alliance/makevbe/vsclib200/xnr2v8x05.bash
	echo "# Remake xnr2v8x05.vbe"
xnr3v1x05.vbe: ../../../alliance/makevbe/vsclib200/xnr3v1x05.bash
	echo "# Remake xnr3v1x05.vbe"
xnr3v1x1.vbe: ../../../alliance/makevbe/vsclib200/xnr3v1x1.bash
	echo "# Remake xnr3v1x1.vbe"
xnr3v1x2.vbe: ../../../alliance/makevbe/vsclib200/xnr3v1x2.bash
	echo "# Remake xnr3v1x2.vbe"
xooi21v0x05.vbe: ../../../alliance/makevbe/vsclib200/xooi21v0x05.bash
	echo "# Remake xooi21v0x05.vbe"
xooi21v0x1.vbe: ../../../alliance/makevbe/vsclib200/xooi21v0x1.bash
	echo "# Remake xooi21v0x1.vbe"
xooi21v0x2.vbe: ../../../alliance/makevbe/vsclib200/xooi21v0x2.bash
	echo "# Remake xooi21v0x2.vbe"
xoon21v0x05.vbe: ../../../alliance/makevbe/vsclib200/xoon21v0x05.bash
	echo "# Remake xoon21v0x05.vbe"
xoon21v0x1.vbe: ../../../alliance/makevbe/vsclib200/xoon21v0x1.bash
	echo "# Remake xoon21v0x1.vbe"
xoon21v0x2.vbe: ../../../alliance/makevbe/vsclib200/xoon21v0x2.bash
	echo "# Remake xoon21v0x2.vbe"
xoon21v0x3.vbe: ../../../alliance/makevbe/vsclib200/xoon21v0x3.bash
	echo "# Remake xoon21v0x3.vbe"
xor2v0x05.vbe: ../../../alliance/makevbe/vsclib200/xor2v0x05.bash
	echo "# Remake xor2v0x05.vbe"
xor2v0x1.vbe: ../../../alliance/makevbe/vsclib200/xor2v0x1.bash
	echo "# Remake xor2v0x1.vbe"
xor2v0x2.vbe: ../../../alliance/makevbe/vsclib200/xor2v0x2.bash
	echo "# Remake xor2v0x2.vbe"
xor2v0x3.vbe: ../../../alliance/makevbe/vsclib200/xor2v0x3.bash
	echo "# Remake xor2v0x3.vbe"
xor2v0x4.vbe: ../../../alliance/makevbe/vsclib200/xor2v0x4.bash
	echo "# Remake xor2v0x4.vbe"
xor2v0x6.vbe: ../../../alliance/makevbe/vsclib200/xor2v0x6.bash
	echo "# Remake xor2v0x6.vbe"
xor2v1x05.vbe: ../../../alliance/makevbe/vsclib200/xor2v1x05.bash
	echo "# Remake xor2v1x05.vbe"
xor2v1x1.vbe: ../../../alliance/makevbe/vsclib200/xor2v1x1.bash
	echo "# Remake xor2v1x1.vbe"
xor2v2x05.vbe: ../../../alliance/makevbe/vsclib200/xor2v2x05.bash
	echo "# Remake xor2v2x05.vbe"
xor2v2x1.vbe: ../../../alliance/makevbe/vsclib200/xor2v2x1.bash
	echo "# Remake xor2v2x1.vbe"
xor2v2x2.vbe: ../../../alliance/makevbe/vsclib200/xor2v2x2.bash
	echo "# Remake xor2v2x2.vbe"
xor2v3x1.vbe: ../../../alliance/makevbe/vsclib200/xor2v3x1.bash
	echo "# Remake xor2v3x1.vbe"
xor2v4x1.vbe: ../../../alliance/makevbe/vsclib200/xor2v4x1.bash
	echo "# Remake xor2v4x1.vbe"
xor2v5x1.vbe: ../../../alliance/makevbe/vsclib200/xor2v5x1.bash
	echo "# Remake xor2v5x1.vbe"
xor2v6x1.vbe: ../../../alliance/makevbe/vsclib200/xor2v6x1.bash
	echo "# Remake xor2v6x1.vbe"
xor2v7x1.vbe: ../../../alliance/makevbe/vsclib200/xor2v7x1.bash
	echo "# Remake xor2v7x1.vbe"
xor2v8x05.vbe: ../../../alliance/makevbe/vsclib200/xor2v8x05.bash
	echo "# Remake xor2v8x05.vbe"
xor2v8x1.vbe: ../../../alliance/makevbe/vsclib200/xor2v8x1.bash
	echo "# Remake xor2v8x1.vbe"
xor2v8x2.vbe: ../../../alliance/makevbe/vsclib200/xor2v8x2.bash
	echo "# Remake xor2v8x2.vbe"
xor3v0x05.vbe: ../../../alliance/makevbe/vsclib200/xor3v0x05.bash
	echo "# Remake xor3v0x05.vbe"
xor3v1x05.vbe: ../../../alliance/makevbe/vsclib200/xor3v1x05.bash
	echo "# Remake xor3v1x05.vbe"
xor3v1x1.vbe: ../../../alliance/makevbe/vsclib200/xor3v1x1.bash
	echo "# Remake xor3v1x1.vbe"
xor3v1x2.vbe: ../../../alliance/makevbe/vsclib200/xor3v1x2.bash
	echo "# Remake xor3v1x2.vbe"
