#!/bin/bash

rm -f *.vbe

cp -p ../sxlib013_6/a2_x2.vbe .
cp -p ../sxlib013_6/a3_x2.vbe .
cp -p ../sxlib013_6/a4_x2.vbe .
cp -p ../sxlib013_6/an12_x1.vbe .
cp -p ../sxlib013_6/ao22_x2.vbe .
cp -p ../sxlib013_6/ao2o22_x2.vbe .
cp -p ../sxlib013_6/buf_x2.vbe .
cp -p ../sxlib013_6/inv_x1.vbe .
cp -p ../sxlib013_6/mx2_x2.vbe .
cp -p ../sxlib013_6/na2_x1.vbe .
cp -p ../sxlib013_6/na3_x1.vbe .
cp -p ../sxlib013_6/na4_x1.vbe .
cp -p ../sxlib013_6/nao22_x1.vbe .
cp -p ../sxlib013_6/nao2o22_x1.vbe .
cp -p ../sxlib013_6/nmx2_x1.vbe .
cp -p ../sxlib013_6/no2_x1.vbe .
cp -p ../sxlib013_6/no3_x1.vbe .
cp -p ../sxlib013_6/no4_x1.vbe .
cp -p ../sxlib013_6/noa22_x1.vbe .
cp -p ../sxlib013_6/noa2a22_x1.vbe .
cp -p ../sxlib013_6/nxr2_x1.vbe .
cp -p ../sxlib013_6/o2_x2.vbe .
cp -p ../sxlib013_6/o3_x2.vbe .
cp -p ../sxlib013_6/o4_x2.vbe .
cp -p ../sxlib013_6/oa22_x2.vbe .
cp -p ../sxlib013_6/oa2a22_x2.vbe .
cp -p ../sxlib013_6/on12_x1.vbe .
cp -p ../sxlib013_6/one_x0.vbe .
cp -p ../sxlib013_6/rowend_x0.vbe .
cp -p ../sxlib013_6/tie_x0.vbe .
cp -p ../sxlib013_6/xr2_x1.vbe .
cp -p ../sxlib013_6/zero_x0.vbe .

ls -1 *.vbe | sed 's/\.vbe/ C/' > SXLIB013_6_MIN
ls -1 rowend*.vbe | sed 's/\(.*\)\.vbe/\1 F/' >> SXLIB013_6_MIN
ls -1 tie*.vbe | sed 's/\(.*\)\.vbe/\1 F/' >> SXLIB013_6_MIN
